tools/importer-rest-api-specs/components/schema/fields_top_level.go
tools/importer-rest-api-specs/components/schema/helpers.go
tools/importer-rest-api-specs/components/schema/helpers_test.go

This PR fixes a couple of issues spotted whilst reviewing the documentation:
```
* `identity` - (Optional) 
```
and
```
* `client_id` - The id of the app associated with the identity. 
* `principal_id` - The id of the service principal object associated with the created identity.
* `tenant_id` - The id of the tenant which the identity belongs to.
```
these are now output as:
> Specifies the Managed Identity which should be assigned to this Load Test.
> The ID of the app associated with the Identity.
> The ID of the Service Principal object associated with the created Identity.
> The ID of the Tenant which the Identity belongs to.

documentation: minor fixes

---

config/resource-manager.hcl

This is a new resource requested by service team. The GA date is 9/30.
[Swagger](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/deviceupdate/resource-manager/Microsoft.DeviceUpdate/stable/2022-10-01)
[Document](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/create-device-update-account)

config: add `deviceupdate` @ `2022-10-01`

---

config/resource-manager.hcl

swagger: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/azurestackhci/resource-manager/Microsoft.AzureStackHCI/stable/2022-09-01
doc: https://learn.microsoft.com/en-us/azure-stack/hci/

config: add `azurestackhci` @ `2022-09-01`

---

tools/importer-rest-api-specs/components/parser/models.go
tools/importer-rest-api-specs/components/parser/models_test.go
tools/importer-rest-api-specs/components/parser/testdata/model_containing_allof_within_properties.json

fixes #1714
```csharp
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Pandora.Definitions.Attributes;
using Pandora.Definitions.Attributes.Validation;
using Pandora.Definitions.CustomTypes;
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.
namespace Pandora.Definitions.ResourceManager.SecurityInsights.v2021_09_01_preview.AlertRuleTemplates;
internal class MLBehaviorAnalyticsAlertRuleTemplatePropertiesModel
{
[JsonPropertyName("alertRulesCreatedByTemplateCount")]
[Required]
public int AlertRulesCreatedByTemplateCount { get; set; }
[DateFormat(DateFormatAttribute.DateFormat.RFC3339)]
[JsonPropertyName("createdDateUTC")]
public DateTime? …
```

importer-rest-api-specs: process nested fields from `allOf` models

---

data/Pandora.Api/V1/ResourceManager/Terraform.cs
data/Pandora.Data/Models/TerraformResourceDefinition.cs
data/Pandora.Data/Transformers/ServiceTests.cs
data/Pandora.Data/Transformers/TerraformResourceDefinition.cs
data/Pandora.Data/Transformers/TerraformResourceDefinitionTests.cs
data/Pandora.Definitions.ResourceManager/LoadTestService/Terraform/LoadTest-Resource.cs
data/Pandora.Definitions.ResourceManager/ManagedIdentity/Terraform/UserAssignedIdentity-Resource.cs
data/Pandora.Definitions/Interfaces/TerraformResourceDefinition.cs
tools/generator-terraform/generator/resource/docs/component_example_usage.go
tools/generator-terraform/generator/resource/docs/component_example_usage_test.go
tools/importer-rest-api-specs/components/dataapigenerator/templater_terraform_resource_definition.go
tools/importer-rest-api-specs/pipeline/run_importer.go
tools/importer-rest-api-specs/pipeline/task_generate_terraform_example_usage.go
tools/importer-rest-api-specs/pipeline/task_generate_terraform_example_usage_test.go

This PR refactors the Example Usage Generation to be done in `tools/importer-rest-api-specs` so that we can include this in the Data API and proof this - meaning that we'll catch #1720.
Once this PR is merged we can look to fix #1720, but I figured this is worth refactoring first so that we can fix why we missed this bug in the first place.

refactor: moving Example Usage Generation into `tools/importer-rest-api-specs`

---

tools/importer-rest-api-specs/components/parser/helpers.go
tools/importer-rest-api-specs/components/parser/normalization.go
tools/importer-rest-api-specs/components/parser/parser.go
tools/importer-rest-api-specs/components/parser/swagger_tags.go
tools/importer-rest-api-specs/components/parser/swagger_tags_test.go
tools/importer-rest-api-specs/components/parser/testdata/operations_single_tag_different_casing.json

This fixes an issue when importing `Kusto` where the Scripts Operations are defined both within the Swagger Tag `scripts` and `Scripts` - by normalising the Swagger tag to `Scripts`.
Fixes #1727

tools/importer-rest-api-specs: parsing operations from the Swagger tags when the Operations use the same tag in different casing

---

data/Pandora.Data/Helpers/Type.cs

Reset this change but meant to commit/push it, this change means that we don't erroneously output Zones as a Model (https://github.com/hashicorp/go-azure-sdk/pull/198/files#diff-0fcb75d1dbaf606e6b83b826a2d2fa4c70fd98e70644a2742123e0da79b21225R6-R7) but rather as a Custom Type

data: Zone and Zones are custom types

---

data/Pandora.Api/V1/ResourceManager/Terraform-Models.cs
data/Pandora.Api/V1/ResourceManager/Terraform.cs
data/Pandora.Data/Models/TerraformSchemaObjectDefinition.cs
data/Pandora.Data/Transformers/TerraformSchemaObjectDefinition.cs
data/Pandora.Data/Transformers/TerraformSchemaObjectDefinitionTests.cs
tools/generator-terraform/generator/helpers/object_definition.go
tools/generator-terraform/generator/pluginsdkattributes/plugin_sdk_attributes.go
tools/importer-rest-api-specs/components/dataapigenerator/templater_terraform_resource_schema.go
tools/importer-rest-api-specs/components/parser/cleanup/cleanup.go
tools/importer-rest-api-specs/components/schema/object_definition.go
tools/sdk/resourcemanager/terraform.go

This PR adds support for Dictionaries to the Terraform Schema in both the `importer-rest-api-specs` tool and the `Data API` such we can look to output these.
At this point in time no Resources make use of this, so whilst this is incomplete (and the remaining mappings work is tracked in #1777) - this isn't currently threaded through end-to-end and thus isn't usable at this time.
An example Resource which uses this is DeveloperHub:
```hcl
service "DevHub" {
terraform_package = "developerhub"
api "2022-04-01-preview" {
package "Workflow" {
definition "developerhub_workflow" {
id = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevHub/workflows/{workflowName}"
display_name = "Developer Hub Workflow"
website_subcategory = "Developer Hub"
description = …
```

tools/importer-rest-api-specs / Data API: initial support for Dictionaries in the Schema

---

tools/generator-terraform/generator/resource/component_update_func.go
tools/generator-terraform/generator/resource/component_update_func_test.go
tools/importer-rest-api-specs/components/parser/swagger_data_workarounds.go
tools/importer-rest-api-specs/components/schema/fields_nested.go
tools/importer-rest-api-specs/components/testattributes/test_attributes.go
tools/importer-rest-api-specs/components/testattributes/test_attributes_test.go

This PR includes a number of fixes to both `importer-rest-api-specs` and `generator-terraform`:
1. Ensures that we output the Mappings in the Terraform Generator for an Update function where the SDK Model is shared between a Create and Update
2. `tools/importer-rest-api-specs`: outputting the referenced model name for `ModelToModel` mappings rather than computing it (which maybe wrong if this has been renamed)
3. `tools/importer-rest-api-specs`: outputs the value `acctest` in the Test HCL for fields named `dns_prefix` (there's several of these, and they're prefixes, so this is fine)
4. `tools/importer-rest-api-specs`: handling an optional field containing a required field (such that the block is ultimately required)

`importer-rest-api-specs` and `generator-terraform`: various fixes

---

config/resources/containerservice.hcl
tools/importer-rest-api-specs/components/dataapigenerator/templater_terraform_resource_schema.go
tools/importer-rest-api-specs/components/parser/swagger_data_workarounds.go

This PR introduces support for Kubernetes Fleet Manager, which is in Preview.
There's an upstream issue in the Swagger, which is fixed in this PR: https://github.com/Azure/azure-rest-api-specs/pull/21394
To workaround that in the interim this PR includes an override to allow us to generate this resource.

New Resource: generating Kubernetes Fleet Manager

---

config/resources/containerservice.hcl

config: fixing the website category for Kubernetes Fleet Manager

---

config/resources/containerservice.hcl
tools/importer-rest-api-specs/components/dataapigenerator/templater_terraform_resource_definition.go

This PR adds a disclaimer that the Kubernetes Fleet Manager resource is in Preview - and adds support for multi-line descriptions.
Whilst longer-term I have a feeling we'll want to expose Preview information in a different manner, this should be fine in the interim.

`kubernetes_fleet_manager` - outputting that this is in Preview

---

tools/generator-terraform/generator/resource/docs/component_frontmatter.go

Whilst we could output the regular description here this isn't necessarily valid as YAML FrontMatter - which causes this linting error:
`* website/docs/r/kubernetes_fleet_manager.html.markdown: error checking file frontmatter: error parsing YAML frontmatter: yaml: line 9: could not find expected ':'`
As such this commit changes to using a pre-formatted string for the frontmatter description which whilst isn't perfect (grammatically) works well enough for now
Fixes https://github.com/hashicorp/terraform-provider-azurerm/actions/runs/3395699863/jobs/5645911212

tools/generator-terraform: outputting the resource Display Name as the description

---

config/resource-manager.hcl

adding recoveryservicessiterecovery@2022-05-01 to enable new features of recovery services
the name consistency issue of #1672 has been fixed

add `recoveryservicessiterecovery@2022-05-01`

---

config/resource-manager.hcl
tools/version-bumper/main.go

This PR enables the auto-onboarding of new API Versions for Services which have been imported into Pandora.
This means that should a new API Version become available, and we've not explicitly marked it as that it should be being ignored, that a PR will be sent to add the new API Version to the config when the Swagger is updated.

tools/version-bumper: auto-onboarding new versions of existing APIs

---

data/Pandora.Definitions/Operations/GetOperation.cs
tools/importer-rest-api-specs/components/dataapigenerator/templater_operation.go
tools/importer-rest-api-specs/components/parser/operations.go
tools/importer-rest-api-specs/components/parser/operations_test.go
tools/importer-rest-api-specs/components/parser/testdata/operation_content_types.json

Spotted whilst reviewing #1756 that we're not currently outputting the Content-Type into the Data API, as such we're always outputting JSON regardless of what the operation supports.
This PR fixes this, so that we can use this information down the line - and also fixes a bug where the Consumes and Produces in the Swagger were being parsed the wrong way around (such that we want to parse the Consumes from a PUT/POST etc, and the Consumes from a HEAD/GET)

tools/importer-rest-api-specs: surfacing the `Content-Type` as required

---

tools/importer-rest-api-specs/components/dataapigenerator/templater_operation.go

`\t` can only be used inside of a literal string value (e.g. contained within `"`), but we're intentionally not using that here as such this reverts the previous change for now.
Fixes #1846

tools/importer-rest-api-specs: fixing a bug where strings were output with the literal `\t` rather than tabs

---

tools/generator-go-sdk/generator/templater_models.go
tools/generator-go-sdk/generator/templater_models_test.go

Unfortunately there's a number of APIs this causes issues with (DataBricks, Media, Mixed Reality and Notification Hubs) as such we'll want to revert this for now, raise API issues, then look to re-introduce this

tools/generator-go-sdk: reverting the `optional object` logic for now

---

tools/importer-rest-api-specs/components/parser/cleanup/cleanup.go

tools/importer-rest-api-specs: normalizing `Vm`, `Vmss` and `Cpu`

---

config/resource-manager.hcl

cont. of #1553 which was reverted
This was once removed due to eventual consistency issue in #1578. Now that the change https://github.com/hashicorp/pandora/commit/4f5ec640fce1c9dd4052db6fc2a48bf9c5142a88 mentioned in the regenerating pr has been merged, assuming #1579 is resolved so that this api version could be added back.

config: add compute @ 2022-03-01

---

config/resource-manager.hcl

per the comments (https://github.com/hashicorp/terraform-provider-azurerm/pull/19294#issuecomment-1333905390), add recoveryservices@2021-08-01

add recoveryservices@2021-08-01

---

tools/generator-go-sdk/generator/templater_methods_autorest.go
tools/generator-go-sdk/generator/templater_methods_autorest_test.go
tools/generator-go-sdk/main.go

tools/generator-go-sdk: conditionally renaming the response struct if it conflicts with a model

---

tools/importer-rest-api-specs/components/parser/operations.go
tools/importer-rest-api-specs/components/parser/operations_test.go
tools/importer-rest-api-specs/components/parser/testdata/operations_single_multiple_return_objects.json

When the operation has multiple response objects, we pick the lowest status code where possible.
As a general rule this should be a 200/201, but this works around operations having different response objects for different operations, since we only parse the HTTP Response when we're expecting a 200.
When a single response object is returned we parse the status code regardless, so this change is limited to operations with multiple status codes.
Fixes the issues seen in #1984

tools/importer-rest-api-specs: handling the responses having multiple response objects

---

config/resource-manager.hcl

Hi,
This PR is to create a newer version of the authorization api so that I can make a resource for Role Eligibility Schedule Requests for PIM on Azure Resources.
Would you recommend to use the latest version, i.e. `2022-04-01-preview` or `2020-10-01` as it's stable?
Cheers

feat: create authorization service version 2020-10-01

---

config/resource-manager.hcl

We don't need these at this time, so I'm going to ignore these for now

config: ignoring some new api versions for now

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_inconsistent_swagger_segments.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go

This PR dynamically renames the `UserSpecifiedSegment` keys to match the preceding Static Segment value where possible - for example a Resource ID in the form `/static/{value}` will be updated to `/static/{staticName}`.
Whilst this may seem pedantic, this fixes the repeated inconsistencies seen here where the API Definitions define the same Resource ID using different segments:
https://github.com/hashicorp/pandora/pull/2010/files#diff-aad1409e4b94d6c75f639fd03d2f0f44ed8672f62ca8944813b05e50f4f48817L15-R15
---
This is going to introduce a lot of changes to the generated SDK.. however this one-time breaking change should mostly remove the Swagger issues we're facing when the Segment Values don't align - which feels like a valuable tradeoff - however some usages may need fixing as a result.

tools/importer-rest-api-specs: rewriting the Resource ID segments to be consistent

---

docs/resource-manager-service-import.md
tools/importer-rest-api-specs/components/parser/helpers_test.go
tools/importer-rest-api-specs/components/parser/load_and_parse.go
tools/importer-rest-api-specs/components/parser/parser.go
tools/importer-rest-api-specs/components/parser/parser_test.go
tools/importer-rest-api-specs/pipeline/task_parse_data.go
tools/sdk/config/services/model.go

Some Azure Services define operations outside of their Resource Provider, for example the `network` service includes operations from both `Microsoft.Compute` and `Microsoft.Network` - which causes issues when parsing since duplicate Resource ID names are parsed out (#1223).
This PR adds support for optionally filtering the Resource IDs imported to just those which match the Resource Provider listed in `./config/resource-manager.hcl` - which avoids the issue by filtering these Resource ID's out. Whilst this isn't something we want to do for every Service, doing so allows us to skip these 4 operations which aren't relevant to us - which allows us to import `network`.
Fixes #1223

tools/importer-rest-api-specs: support for filtering operations outside of the specified Resource Provider

---

config/resource-manager.hcl

These aren't currently needed, so ignoring these until they are

config: ignoring new versions for now

---

config/resource-manager.hcl
tools/importer-rest-api-specs/components/parser/cleanup/cleanup.go

This fixes data inconsistencies, see #2060 for details

tools/importer-rest-api-specs: updating `openshiftclusters` -> `openShiftClusters`

---

config/resources/managedidentity.hcl
tools/importer-rest-api-specs/components/parser/resourceids/common_id_user_assigned_identity.go
tools/importer-rest-api-specs/components/parser/resourceids/common_id_user_assigned_identity_test.go

Matching the behaviour introduced in hashicorp/pandora#2011 which unblocks fixing https://github.com/hashicorp/pandora/actions/runs/4073772510
Dependent on https://github.com/hashicorp/go-azure-helpers/pull/147 / being fixed in `terraform-provider-azurerm`

terraform: updating the segments for User Assigned Identity ID

---

config/resource-manager.hcl

Used for the `azurerm_kubernetes_service_versions` data source

containerservice: adding support for API Version `2019-08-01`

---

tools/importer-rest-api-specs/pipeline/run_importer.go

When a service is split-up into different sub-groupings within the Swagger, we need to account for the fact that an API version may not be available in all of the sub-groups.
This fixes an issue introduced in https://github.com/Azure/azure-rest-api-specs/pull/22428 where the Media Service has introduced a new sub-group with no Swagger files, meaning importing this currently panics:
```
2023-02-08T11:36:08.401Z [INFO]  Importer for Service "Media".Importer for API Version "2022-08-01": 😵 Service "Media" / Api Version "2022-08-01" contains no resources, skipping.
215
panic: runtime error: invalid memory address or nil pointer dereference
216
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xac65d4]
217
218
goroutine 1 [running]:
219 …
```

tools/importer: fixing a crash when there's no files for a given API Version

---

tools/importer-rest-api-specs/pipeline/task_generate_terraform_example_usage.go
tools/importer-rest-api-specs/pipeline/task_generate_terraform_example_usage_test.go

I looked into using `hclwrite` and `hclparse` here, whilst we should take that approach it's significantly more involved and likely wants to instead be done at the same time as the test generation itself - as such for now this is a special-case for the `azurerm_load_test` resource.
Fixes https://github.com/hashicorp/terraform-provider-azurerm/pull/20389

tools/importer-rest-api-specs: accounting for `azurerm_load_test` being a special-case when generating the examples

---

config/resource-manager.hcl

Adding 2022-02-01 for upgrading to pandora sdk in azurerm project.
1. Swagger Link: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/azure-kusto/resource-manager/Microsoft.Kusto/stable
2. Doc Link: https://learn.microsoft.com/en-us/rest/api/azurerekusto/clusters/create-or-update?tabs=HTTP

Add `Kusto` version `2022-02-01`

---

tools/generator-go-sdk/generator/data.go
tools/generator-go-sdk/generator/settings.go
tools/generator-go-sdk/main.go

And add Automation@2022-08-08 with the new base layer. this version has not been used in `azurerm` for the current main and it will fix some SDK issues when working with https://github.com/hashicorp/go-azure-sdk/pull/298.

`generator-go-sdk`: ServicesUsingNewBaseLayer support with specific api version

---

tools/generator-go-sdk/generator/settings.go
tools/generator-go-sdk/generator/templater_meta_client.go
tools/generator-go-sdk/main.go

This PR fixes a bug introduced in #2112 where the Meta Client wasn't being output using the new base layer - since this is output separately to each Resource within an API Version and needs to be output separately.

tools/generator-go-sdk: checking both the service and api version for the new base layer flag

---

config/resource-manager.hcl

rationale: some SSL settings that people have been waiting for forever are only implemented in preview API. You can use those features in the portal, but not via GA API, so I wanna add preview SDK as well to be able to implement those features.

`mariadb`: add `2018-06-01-preview`

---

tools/generator-go-sdk/generator/templater_id_parser.go
tools/generator-go-sdk/generator/templater_id_parser_test.go
tools/generator-go-sdk/generator/templater_id_parser_tests.go
tools/generator-go-sdk/generator/templater_meta_client.go
tools/generator-go-sdk/generator/templater_meta_client_autorest.go
tools/generator-go-sdk/generator/templater_predicates.go

This PR fixes a few issues spotted in https://github.com/hashicorp/go-azure-sdk/pull/337 where the ID Parsers, ID Parser Tests, Predicates and Meta Client files weren't being output with the expected copyright headers.
Once this PR is merged, `hashicorp/go-azure-sdk` will be regenerated to include these changes, meaning that https://github.com/hashicorp/go-azure-sdk/pull/337 will also get regenerated to only target the `.github` folder (which is fine) - so we can close https://github.com/hashicorp/go-azure-sdk/pull/337 in favour of this PR (which, once merged will generate the same fixes)

tools/generator-go-sdk: adding the missing copyright lines to the ID Parsers, Tests, Predicates and Meta Clients

---

tools/importer-rest-api-specs/components/parser/resourceids/common_id_key_vault.go
tools/importer-rest-api-specs/components/parser/resourceids/common_id_key_vault_key.go
tools/importer-rest-api-specs/components/parser/resourceids/common_ids.go

Should fix the flip-flopping seen in https://github.com/hashicorp/pandora/pull/2181/

tools/importer-rest-api-specs: supporting using Common IDs for Key Vault and Key Vault Key

---

tools/generator-go-sdk/generator/templater_methods_autorest.go
tools/generator-go-sdk/generator/templater_methods_autorest_test.go

fix https://github.com/hashicorp/go-azure-sdk/issues/354
related to https://github.com/hashicorp/terraform-provider-azurerm/issues/20811
the error from autorest was covered by the unmarshal func before.

`generator-go-sdk`: fix a bug when generating with discriminatedType

---

tools/generator-go-sdk/main.go

Can be revisited once https://github.com/hashicorp/go-azure-sdk/issues/356 has been fixed

tools/generator-go-sdk: reverting `Portal` from using the new base layer for now

---

config/resource-manager.hcl

swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/mediaservices/resource-manager/Microsoft.Media/Encoding/stable/2022-07-01/Encoding.json
Resources using `2021-11-01`:
1. `azurerm_media_transform` and `azurerm_media_job`,  will be upgraded to `2022-07-01` after this PR.
2. `azurerm_media_services_account`, will be upgraded to `2023-01-01` in the future.

Config: add `mediaservices@2022-07-01`

---

tools/generator-go-sdk/generator/templater_meta_client.go
tools/generator-go-sdk/generator/templater_meta_client_autorest.go

This allows `hashicorp/copywrite` to detect them so these aren't auto-fixed - fixes the `resource-manager/` part of https://github.com/hashicorp/go-azure-sdk/pull/347/files#diff-5edeb24113b44f80e88fb1135e594743719a72e1b63c7cd15d738eda8d763784

tools/generator-go-sdk: moving the copyright headers up

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_datafactory_23013.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go

This PR works around [this Swagger issue](https://github.com/Azure/azure-rest-api-specs/pull/23013) where Discriminated Types aren't modelled correctly.

tools/importer-rest-api-specs: working around https://github.com/Azure/azure-rest-api-specs/pull/23013

---

tools/generator-go-sdk/main.go
tools/generator-terraform/generator/definitions/template_client_registration.go
tools/generator-terraform/generator/definitions/template_client_registration_test.go
tools/generator-terraform/generator/definitions/template_service_client.go
tools/generator-terraform/generator/definitions/template_service_client_test.go

This PR adds support for the generated resources using either `Azure/go-autorest` or `hashicorp/go-azure-sdk` by conditionally calling the correct Meta Client.
This'll need a little coordination in `terraform-provider-azurerm`, since [the `buildAutoClients` method](https://github.com/hashicorp/terraform-provider-azurerm/blob/6c991f7808ad32cfd77d085f604d08cad584069e/internal/clients/client.go#L260) will need to raise the error.

tools/generator-terraform: output the sdk client using the new base layer/add an error to the old base layer method

---

tools/generator-go-sdk/main.go

Since it's a little late in the week for it, we'll merge this after this weeks release

tools/generator-go-sdk: updating `databricks` to use the new base layer

---

data/Pandora.Definitions/Operations/PatchOperation.cs

API spec for ContainerRegistry 2021-08-01-preview has a long running PATCH operation that can return two response codes:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2021-08-01-preview/containerregistry.json#L1332-L1382

Add status code 201 to the base class for patch operations

---

tools/importer-rest-api-specs/components/parser/load_and_parse.go

under my local machine test, it saves nearly half time-cost while import the `apimanagement` service(with 43 swagger files).
```
before: 2023/03/30 15:02:06 import time cost: 31.356828085s
after:  2023/03/30 15:02:47 import time cost: 17.37163013s
```

`importer-rest-api-specs`: reuse the result of loaded swagger file to speedup

---

config/resource-manager.hcl

Imports the 2021-04-01 version of resources API so that I can leverage https://learn.microsoft.com/en-us/rest/api/resources/deployment-operations List endpoint

Add 2021-04-01 Resources API

---

data/Pandora.Definitions/Interfaces/ResourceDefinition.cs
tools/importer-rest-api-specs/components/dataapigenerator/package.go
tools/importer-rest-api-specs/components/dataapigenerator/templater_package_definition.go

This PR introduces a little more overhead at compile-time to save time at run-time - by statically defining the list of Constants and Models used in each API Resource, we can avoid using reflection to pull this out.
I've intentionally split this change out from the separate change in the Data API since it's going to require a change to the entire `./data/Pandora.Definitions.ResourceManager` package, so by merging this change first we can add this data, then add these new fields to the interface (in the next PR) and make use of this information.
The associated change for this in the Data API should be fairly minimal (see below), however this will necessitate rewriting the unit tests to account for these models now being defined by the Resource Definition, rather than being looked up via …

`tools/importer-rest-api-specs`: outputting the list of Constants and Models used in each API Resource

---

tools/generator-go-sdk/featureflags/flags.go
tools/generator-go-sdk/generator/templater_constant.go
tools/generator-go-sdk/generator/templater_constant_test.go
tools/generator-go-sdk/generator/templater_constants.go
tools/generator-go-sdk/generator/templater_constants_test.go

Skimming #758 I realised there's a far simpler way of doing this - hence this PR.
This PR introduces a custom unmarshal function for string constants, meaning that when we unmarshal the JSON response from the API, we'll try and normalize this value to match the casing defined within the API Specification.
As a hypothetical example, this means that is the API Specification defines `sku` with the values `Standard` and `Premium` - if the API response returns `standard` or `Standard` or `StAnDaRd` then we'll unmarshal this value consistently as `Standard`.
Notably, this change only takes effect at Unmarshal time, since we assume that the payload being provided in the HTTP Response is cased correctly, as in the Terraform Provider, the schema should be validating the value being provided …

tools/generator-go-sdk: normalizing the value of String constants during unmarshalling

---

tools/generator-go-sdk/generator/templater_constant.go
tools/generator-go-sdk/generator/templater_constant_test.go
tools/generator-go-sdk/generator/templater_constants.go
tools/generator-go-sdk/generator/templater_constants_test.go
tools/generator-go-sdk/go.mod
tools/generator-go-sdk/go.sum

These functions are needed in two cases:
1. When the Constant is a String, the `parse[Constant]` function is used during Normalization
2. When the Constant is used within a Resource ID, the `parse[Constant]` function is used within the Resource ID parse function
Whilst we could always output these parse functions, conditionally outputting these reduces the TLOC we're outputting, which keeps the Go Module size of `hashicorp/go-azure-sdk` down.
Fixes https://github.com/hashicorp/go-azure-sdk/actions/runs/4615982722?pr=400

tools/generator-go-sdk: conditionally outputting the `parse[Constant]` functions

---

tools/importer-rest-api-specs/GNUmakefile
tools/importer-rest-api-specs/components/parser/swagger_tags.go
tools/importer-rest-api-specs/components/parser/swagger_tags_test.go
tools/importer-rest-api-specs/components/parser/testdata/operations_on_resources.json

importer-rest-api-specs: remove `operations` from tags that we filter out

---

data/Pandora.Definitions.HandDefined/AADB2C/v2021_04_01_preview/Tenants/Definition.cs

These are hand-defined and completes the back-porting of this information, so the next PR can follow up and map these directly, rather than reflecting into these

data: defining the Constants and Models used by the HandDefined API Definition (AADB2C)

---

tools/generator-go-sdk/featureflags/flags.go
tools/generator-go-sdk/generator/templater_models.go
tools/generator-go-sdk/generator/templater_models_discriminators_test.go

This change is impactful and needs to be rolled out Service Package by Service Package, as such we're going to temporarily disable this to allow us to update the SDK, and then once that's done we can look to enable this Service by Service by using the `new base layer` feature toggle to let us make those changes.

tools/generator-go-sdk: disabling / feature-flagging the discriminator change from #2320 for now

---

tools/generator-go-sdk/generator/templater_methods.go
tools/generator-go-sdk/generator/templater_methods_test.go

I've vendored the generated output of this into `terraform-provider-azurerm`, enabling the new base layer for `DataShare` and the test passes when updating the client:
```
$ TF_ACC=1 envchain azurerm go test -v ./internal/services/datashare/... -run=TestAccDataShareDatasetDataLakeGen2DataSource_basic
=== RUN   TestAccDataShareDatasetDataLakeGen2DataSource_basic
=== PAUSE TestAccDataShareDatasetDataLakeGen2DataSource_basic
=== CONT  TestAccDataShareDatasetDataLakeGen2DataSource_basic
--- PASS: TestAccDataShareDatasetDataLakeGen2DataSource_basic (357.76s)
```
Fixes https://github.com/hashicorp/go-azure-sdk/issues/437

tools/generator-go-sdk: support for top level discriminated types

---

tools/importer-rest-api-specs/components/parser/models.go
tools/importer-rest-api-specs/components/parser/models_test.go
tools/importer-rest-api-specs/components/parser/testdata/model_single_with_rawfile.json

try to resolve: #2185 
imported cs file:

`importer`:  use `RawFile` instead of `object` for request as object type but format with file

---

tools/generator-go-sdk/main.go

The constant recasing will fix the Azure API issue outlined in https://github.com/hashicorp/terraform-provider-azurerm/issues/21630

tools/generator-go-sdk: updating Search to use the new base layer

---

tools/generator-go-sdk/main.go

Reverts hashicorp/pandora#2490
Blocked on https://github.com/hashicorp/go-retryablehttp/pull/194

Revert "resources: migrating to use the new base layer"

---

config/resource-manager.hcl

Breaking change in https://github.com/Azure/azure-rest-api-specs/pull/23923 since this [got merged when it shouldn't have been](https://github.com/Azure/azure-rest-api-specs/pull/23832#issuecomment-1542321700)

data: removing `maintenance` @ `2023-04-01`

---

config/resource-manager.hcl

This fix only patched `2022-11-01` https://github.com/Azure/azure-rest-api-specs/pull/23738
The ignore was added on https://github.com/hashicorp/pandora/pull/2462, not sure if it has been unblocked.

Config: add `network@2022-11-01`

---

tools/importer-rest-api-specs/components/parser/resourceids/generate_names.go
tools/importer-rest-api-specs/components/parser/resourceids/generate_names_test.go
tools/importer-rest-api-specs/components/parser/resourceids/models.go
tools/importer-rest-api-specs/components/parser/resourceids/parser.go

should resolves: #2265
because the importer tool will find the resource id definition by resource id name when process one tag(Line 260):
https://github.com/hashicorp/pandora/blob/64e4990f726856ce548d5ab3c25f941c5f583211/tools/importer-rest-api-specs/components/parser/remove_unused_items.go#L253-L262
the generated SDK as expected:

`importer-rest-api-specs`: have to update the `ParsedOperation.ResourceIdName` when name conflicts in resourceID

---

tools/importer-rest-api-specs/components/schema/processors/model_flatten_properties_into_parent.go
tools/importer-rest-api-specs/components/schema/processors/model_flatten_properties_into_parent_test.go

This avoids an issue where the same field (say `identity`) may be used both as a top level model and within the nested model - therefore flattening this would replace the top-level object
Fixes #1825

tools/importer-rest-api-specs: only flattening the nested model when the key name is unique

---

tools/importer-rest-api-specs/components/schema/processors/model_flatten_properties_into_parent.go
tools/importer-rest-api-specs/components/schema/processors/model_flatten_properties_into_parent_test.go
tools/importer-rest-api-specs/components/schema/processors/models_test.go

This occurs when the map of keys hasn't been populated yet, thus depending on the ordering this may or may not get flattened, causing issues

tools/importer-rest-api-specs: fixing an eventual consistency bug when parsing the data

---

config/resource-manager.hcl
tools/importer-rest-api-specs/components/parser/internal/helpers.go

There's an issue in the source data where the API operations support different Enum values, thus should be using a different Enum (or as I've done [in this PR](https://github.com/Azure/azure-rest-api-specs/pull/24187) - split this out to a separate endpoint, since it's a separate operation) - as such [this is currently causing flapping in the data](https://github.com/hashicorp/pandora/pull/2557/files#diff-c6309cb7c86d8a927d172057baa8ccc0a5381600b6228e4960994d642895a055L17-R22) - so we're going to need to remove this API version for now.
Once [the upstream PR's been merged](https://github.com/Azure/azure-rest-api-specs/pull/24187), we should be able to re-introduce this API Version.

config: reverting `sql` @ `2022-11-01-preview`

---

tools/generator-terraform/generator/resource/docs/component_arguments.go
tools/generator-terraform/generator/resource/docs/component_arguments_test.go
tools/generator-terraform/generator/resource/docs/component_attributes.go
tools/generator-terraform/generator/resource/docs/component_attributes_test.go
tools/generator-terraform/generator/resource/docs/component_blocks.go
tools/generator-terraform/generator/resource/docs/component_blocks_test.go
tools/generator-terraform/generator/resource/docs/helpers.go

This PR does a few things:
Fixes #2270

tools/generator-terraform: outputting `identity` as blocks in the attributes/arguments - and updating the `block reference`

---

config/resources/loadtestservice.hcl

This commit updates to the latest stable Api version (2022-12-01) however the `encryption` block is currently intentionally being removed due to a conflict - this will be added in the future, but is tracked in #2608
Fixes #2549

`loadtest`: updating to use API Version `2022-12-01`

---

config/resource-manager.hcl

https://github.com/Azure/azure-rest-api-specs/blob/7349b70d60d608ea1c99b837b6372f48db1e27ac/specification/sql/resource-manager/Microsoft.Sql/preview/2021-02-01-preview/ManagedDatabaseSensitivityLabels.json#L62
https://github.com/Azure/azure-rest-api-specs/blob/7349b70d60d608ea1c99b837b6372f48db1e27ac/specification/sql/resource-manager/Microsoft.Sql/preview/2021-02-01-preview/ManagedDatabaseSensitivityLabels.json#LL391C14-L391C14
Swagger PR:
https://github.com/Azure/azure-rest-api-specs/pull/24187

config: remove `sql` due to duplicated and differing definition of SensitivityLabelSource constant

---

tools/importer-rest-api-specs/GNUmakefile

This defaults to 10m, and there's enough data imported that we're now hitting this limit
Supersedes #2649
Fixes the test failure seen once #2648 is opened/run

tools/importer-rest-api-specs: bumping the unit test timeout to 60m

---

tools/importer-rest-api-specs/components/parser/resourceids/common_id_kubernetes_cluster.go
tools/importer-rest-api-specs/components/parser/resourceids/common_ids.go

importer-rest-api-specs: define common id for kubernetes cluster which is a parent resource

---

tools/importer-rest-api-specs/components/parser/resourceids/common_ids.go

Forgot to add these to the `common_ids.go` file.

commonids: add virtual network and subnet to common_ids.go

---

config/resource-manager.hcl

Per discussion in [this PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/22178#discussion_r1244933001), we need to add a new `azurerm_role_assignment_marketplace` resource which uses `go-azure-sdk`.

config: adding new api version for `authorization`

---

config/resource-manager.hcl

We intend to support geoBackupKeyURI and geoBackupUserAssignedIdentityId for the CMK feature. See more details for this request from https://github.com/hashicorp/terraform-provider-azurerm/issues/20750. Now this feature only exists in this latest version.
API Reference: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/preview/2023-03-01-preview/FlexibleServers.json

Config: add Postgresql@2023-03-01-preview

---

tools/importer-rest-api-specs/components/parser/commonschema/custom_field_identity_legacy_system_and_user_assigned_map.go
tools/importer-rest-api-specs/components/parser/models_identity_test.go
tools/importer-rest-api-specs/components/parser/testdata/model_legacy_system_and_user_assigned_map_generic_dictionary.json
tools/importer-rest-api-specs/components/parser/testdata/model_legacy_system_and_user_assigned_map_generic_dictionary_inlined.json

This fixes an issue for DataFactory where the Identity block isn't detected as a CommonSchema block
```diff
diff --git a/data/Pandora.Definitions.ResourceManager/DataFactory/v2018_06_01/Factories/Constant-FactoryIdentityType.cs b/data/Pandora.Definitions.ResourceManager/DataFactory/v2018_06_01/Factories/Constant-FactoryIdentityType.cs
deleted file mode 100644
index e1bfd41ea4..0000000000
--- a/data/Pandora.Definitions.ResourceManager/DataFactory/v2018_06_01/Factories/Constant-FactoryIdentityType.cs
+++ /dev/null
@@ -1,17 +0,0 @@
-using Pandora.Definitions.Attributes;
-using System.ComponentModel;
-
-namespace Pandora.Definitions.ResourceManager.DataFactory.v2018_06_01.Factories;
-
-[ConstantType(ConstantTypeAttribute.ConstantType.String)]
-internal enum FactoryIdentityTypeConstant
-{
- …
```

tools/importer-rest-api-specs: support for identifying generic dictionaries as Legacy User Assigned Identiies

---

tools/version-bumper/config.go
tools/version-bumper/services_resource_manager.go

These also don't import correctly currently due to Swagger issues, however since they're EOL/Deprecated we can skip them

tools/version-bumper: skipping updating services which are EOL/Deprecated/appear to be deprecated when importing the full set

---

data/Pandora.Api/Startup.cs
data/Pandora.Api/V1/Controllers/CommonTypes.cs
data/Pandora.Api/V1/Controllers/ServiceDetails.cs
data/Pandora.Api/V1/Controllers/ServiceVersion.cs
data/Pandora.Data/CommonTypeDefinitions.cs
data/Pandora.Data/DefinitionTypes.cs
data/Pandora.Data/Models/ApiDefinitionsSource.cs
data/Pandora.Data/Models/CommonTypesDefinition.cs
data/Pandora.Data/Repositories/CommonTypesRepository.cs
data/Pandora.Data/Repositories/ICommonTypesRepository.cs
data/Pandora.Data/ServiceDefinitions.cs
data/Pandora.Data/ServiceDefinitionsTests.cs
data/Pandora.Data/Transformers/CommonTypes.cs
data/Pandora.Data/Transformers/Version.cs
data/Pandora.Definitions.MicrosoftGraph.StableV1/MicrosoftGraphStableV1Services.cs
data/Pandora.Definitions/Discovery/CommonTypes.cs
data/Pandora.Definitions/Interfaces/CommonTypesDefinition.cs
data/Pandora.Definitions/Interfaces/Source.cs

Adds an endpoint `/v1/microsoft-graph/{version}/commonTypes` which returns a composite response containing the 'common types' which should be in the `Pandora.Definitions.MicrosoftGraph.{Version}.CommonTypes` namespace.
* Returns only models/constants in this common namespace
* Does not include models/constants defined within a service/version/resource/other namespace
* Does not support any other types
This is intended to provide a mechanism to expose Microsoft Graph named models, which are highly interrelated and form an extensive graph network, making it infeasible to duplicate them between services/resources.
Also adds the API definitions source `MicrosoftGraphMetadata`.
**Example:**
```json
{
"constants": {
"AccessPackageAssignmentState": {
"caseInsensitive": false,
"type": "string", …
```

data-api: support for common types (models and constants)

---

tools/importer-rest-api-specs/components/parser/internal/structs.go
tools/importer-rest-api-specs/models/models.go

Fixes an issue when parsing ContainerApps@2022-11-01-preview and Web@2022-09-01
Unblocks https://github.com/hashicorp/pandora/pull/2734
I've tried adding an acctest to cover this scenario, but I'm struggling to do so due to the normalization - so I've omitted this for now.

tools/importer-rest-api-specs: ModelDefinition comparisons are now more detailed and Reference checks are now case-insensitive

---

config/resource-manager.hcl

No longer used as of https://github.com/hashicorp/terraform-provider-azurerm/pull/22451

config: removing `elastic` @ `2020-07-01`

---

tools/importer-rest-api-specs/components/parser/resource_ids_test.go
tools/importer-rest-api-specs/components/parser/resourceids/parse_segments.go
tools/importer-rest-api-specs/components/parser/testdata/resource_ids_containing_hidden_scope.json
tools/importer-rest-api-specs/components/parser/testdata/resource_ids_containing_hidden_scope_constant.json
tools/importer-rest-api-specs/components/parser/testdata/resource_ids_containing_hidden_scope_hardcoded_provider.json
tools/importer-rest-api-specs/components/parser/testdata/resource_ids_containing_hidden_scope_nested.json
tools/importer-rest-api-specs/components/parser/testdata/resource_ids_containing_hidden_scope_nested_constants.json
tools/importer-rest-api-specs/components/parser/testdata/resource_ids_containing_hidden_scope_nested_hardcoded_provider.json
tools/importer-rest-api-specs/components/parser/testdata/resource_ids_containing_hidden_scope_nested_with_suffix.json
tools/importer-rest-api-specs/components/parser/testdata/resource_ids_containing_hidden_scope_with_suffix.json

This fixes an issue when importing EventGrid, but detects Generic ARM Resource Scopes which are defined as ARM Resources with User Specified Segments (e.g. `/subscriptions/{}/resourceGroups/{}/providers/{}/{}/{}`) instead of Scopes (`/{scope}`). This is also the case for "nested" items (for example `/subscriptions/{}/resourceGroups/{}/providers/{}/{}/{}/{}/{}`)
These should be normalised into the Common ID `ScopeId` - but aren't captured with the Common IDs detection logic
since these can be one of many slightly different formats, so this is easiest to special-case.
Fixes #2341
Fixes #502
Unblocks #2309

`tools/importer-rest-api-specs`: detecting generic ARM Resource scopes

---

tools/importer-rest-api-specs/components/schema/fields_nested.go

The changes made for generating the new resource trusted access role binding will correctly mark the field `hub_profile` and `description` in the other generated resources as `ForceNew: false`, but the functionality for update tests isn't built out enough to handle generating the update tests for these yet so this temporarily overrides the value for ForceNew until we build out the functionality in the tests.

importer-rest-api-specs: ignore fields in existing resources from update payload temporarily

---

tools/importer-rest-api-specs/components/parser/resource_ids_test.go
tools/importer-rest-api-specs/components/parser/resourceids/parse_segments.go
tools/importer-rest-api-specs/components/parser/testdata/resource_ids_containing_hidden_scope_nested_with_extra_segment.json
tools/importer-rest-api-specs/components/parser/testdata/resource_ids_containing_hidden_scope_with_extra_segment.json

This fixes an issue where `/{scope}/{resourceName}` was being output instead of `/{scope}`

tools/importer-rest-api-specs: fixing an issue where Resource IDs which are hidden ARM Scopes are pulled out correctly

---

config/resource-manager.hcl
config/resources/containerservice.hcl

Running the resource tests with 2023-04-02-preview results in an error:
```
=== CONT  TestAccKubernetesClusterTrustedAccessRoleBinding_complete
testcase.go:113: Step 1/2 error: Error running apply: exit status 1
Error: checking for the presence of an existing Trusted Access Role Binding (Subscription: "*******"
Resource Group Name: "/subscriptions/*******/resourceGroups/acctestrg-230718013756695319/providers/Microsoft.ContainerService/managedClusters/acctestaksnzelq"
Managed Cluster Name: "/subscriptions/*******/resourceGroups/acctestrg-230718013756695319/providers/Microsoft.ContainerService/managedClusters/acctestaksnzelq"
Trusted Access Role Binding Name: "acctestkctarb-nzelq"): trustedaccess.TrustedAccessClient#RoleBindingsGet: Failure responding to request: StatusCode=400 -- Original …
```

config: downgrade trusted access binding to `2023-03-02-preview`

---

data/Pandora.Api/V1/Controllers/Terraform-Models.cs

Will fix https://github.com/hashicorp/terraform-provider-azurerm/pull/22635

data api: set json name to `parsedFromParentId`

---

tools/importer-rest-api-specs/components/parser/internal/helpers.go

Web exposes 2 URI's which are GET LRO's but that don't make sense for us to expose:
> /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{siteName}/deploymentStatus/{deploymentStatusId}
and
> /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{siteName}/slots/{slotName}/deploymentStatus/{deploymentStatusId}
Since both of these are LRO's these results should be available instead via the associated Deployment operations, so these LRO's aren't needed.
This fixes an issue when generating the Go SDK, since GET LRO's aren't supported.

tools/importer-rest-api-specs: ignoring the LROs in Web

---

tools/generator-go-sdk/main.go

reverting due to
```
PASS
2023-07-25T17:23:55.7965142Z ok  	github.com/hashicorp/go-azure-sdk/resource-manager/deviceupdate/2023-07-01/privatelinkresources	0.009s
2023-07-25T17:23:57.5233408Z # github.com/hashicorp/go-azure-sdk/resource-manager/devtestlab/2018-09-15
2023-07-25T17:23:57.5313869Z ##[error]resource-manager/devtestlab/2018-09-15/client.go:34:2: environments redeclared in this block
2023-07-25T17:23:57.5321859Z ##[error]	resource-manager/devtestlab/2018-09-15/client.go:15:2: other declaration of environments
2023-07-25T17:23:57.5323030Z ##[error]resource-manager/devtestlab/2018-09-15/client.go:34:2: imported and not used: "github.com/hashicorp/go-azure-sdk/sdk/environments"
2023-07-25T17:23:57.5323968Z ##[error]resource-manager/devtestlab/2018-09-15/client.go:64:44: undefined: …
```

revert devtestlabs back to autorest

---

tools/generator-go-sdk/generator/templater_methods.go
tools/generator-go-sdk/generator/templater_methods_test.go

Fixes https://github.com/hashicorp/pandora/issues/2753

tols/generator-go-sdk: outputting the content type if needed

---

config/resource-manager.hcl

This PR adds legacy 2020-01-01 mysql to pandora. Not sure if this is the right way to do this but it's what we need to migrate mysql over to go-azure-sdk
API Specs for reference https://github.com/Azure/azure-rest-api-specs/tree/7c50841aadb4bfc241de3f09146e1f97ce3583b2/specification/mysql/resource-manager/Microsoft.DBforMySQL/legacy/stable/2020-01-01

Legacy MySQL 2020-01-01

---

config/resource-manager.hcl

We need [legacy 2021-05-01](https://github.com/Azure/azure-rest-api-specs/tree/7c50841aadb4bfc241de3f09146e1f97ce3583b2/specification/mysql/resource-manager/Microsoft.DBforMySQL/legacy/stable/2021-05-01) but we already support a version `2021-05-01`. Is there a way we can point to the legacy version as well?

Remove 2020-01-01 from pandora

---

tools/generator-go-sdk/generator/templater_predicates.go

The bug lead to always return the full list for [ListCompleteMatchingPredicate](https://github.com/hashicorp/terraform-provider-azurerm/blob/34e34b59e68b91b6ec3a1ef91eb871419079a85e/vendor/github.com/hashicorp/go-azure-sdk/resource-manager/appconfiguration/2023-03-01/configurationstores/method_list.go#L70) method.
https://github.com/hashicorp/terraform-provider-azurerm/blob/34e34b59e68b91b6ec3a1ef91eb871419079a85e/vendor/github.com/hashicorp/go-azure-sdk/resource-manager/appconfiguration/2023-03-01/configurationstores/predicates.go#L53
Should be 
```diff
func (p ConfigurationStoreOperationPredicate) Matches(input ConfigurationStore) bool {
-	if p.Id != nil && (input.Id == nil && *p.Id != *input.Id) {
+       if p.Id != nil && (input.Id == nil || *p.Id != *input.Id) {
return false
}
if …
```

tools/generator-go-sdk - fix predicates match condition template

---

config/resource-manager.hcl

These are no longer used and so can be removed

data: removing `network` @ `2022-09-01` and `2022-11-01`

---

tools/generator-go-sdk/main.go

Temporarily leaving API Management since there's a PR in flight to migrate this across/don't want to conflict

tools/generator-go-sdk: porting most of `a` to the new base layer

---

config/resource-manager.hcl

These are no longer used and so can be removed

data: removing `netapp` @ `2021-10-01` and `2022-01-01`

---

tools/generator-go-sdk/main.go

Whilst I was leaving this until the initial PR to port this over to the new SDK was open, turns out we need to fix a recasing issue, so we might as well do this from the start.

tools/generator-go-sdk: updating `apimanagement` to use the new base layer

---

tools/generator-go-sdk/generator/templater_clients.go
tools/generator-go-sdk/generator/templater_clients_test.go
tools/generator-go-sdk/generator/templater_meta_client.go

See: https://github.com/hashicorp/go-azure-sdk/actions/runs/5716954573

tools/generator-go-sdk: fixing an issue where the argument name conflicts with the generated SDK

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_authorization.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go

Upstream PR on `Azure/azure-rest-api-specs`: https://github.com/Azure/azure-rest-api-specs/pull/25080
Fixes https://github.com/hashicorp/go-azure-sdk/issues/288
Diff:
```diff
$ git diff data
diff --git a/data/Pandora.Definitions.ResourceManager/Authorization/v2020_10_01/RoleManagementPolicies/Operation-ListForScope.cs b/data/Pandora.Definitions.ResourceManager/Authorization/v2020_10_01/RoleManagementPolicies/Operation-ListForScope.cs
index de2f049153..0141f63acb 100644
--- a/data/Pandora.Definitions.ResourceManager/Authorization/v2020_10_01/RoleManagementPolicies/Operation-ListForScope.cs
+++ b/data/Pandora.Definitions.ResourceManager/Authorization/v2020_10_01/RoleManagementPolicies/Operation-ListForScope.cs
@@ -20,7 +20,14 @@ internal class ListForScopeOperation : …
```

tools/importer-rest-api-specs: adding a workaround for `authorization`'s missing `$filter`

---

tools/importer-rest-api-specs/components/parser/commonschema/custom_field_identity_user_assigned_map.go
tools/importer-rest-api-specs/components/parser/models_identity_test.go
tools/importer-rest-api-specs/components/parser/testdata/model_user_assigned_map_with_principal_id.json

The storage cache AML file system resource defined UAI with the `principalId` and `tenantId` defined at the top identity model level: https://github.com/Azure/azure-rest-api-specs/blob/14d24d17491d8c2bde24532cb8cc2d663c0ffd9f/specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2023-05-01/amlfilesystem.json#L565.
Without this change, the identity field of the `AMLFileSystem` model will not be defined as the commonschema.
Related to: https://github.com/hashicorp/terraform-provider-azurerm/pull/22680

Importer: Custom filed user assigned identity (map) tolerate exposed principal id at top level

---

config/resource-manager.hcl

Reverts hashicorp/pandora#2813
`Web` is unblocked once https://github.com/hashicorp/go-azure-sdk/pull/561 has been merged, so this can finally go in.

Add support for compute 2023-03-01

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_digitaltwins_25120.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go

Unblocks https://github.com/hashicorp/terraform-provider-azurerm/pull/22782

tools/importer-rest-api-specs: adding a workaround for `digitaltwins`

---

.github/workflows/automation-msgraph-metadata-importer.yaml
.github/workflows/automation-rest-api-specs-importer.yaml

This means the first job to complete would win, the other would fail - and we'd not import all the data

tooling: fixing an issue where the branch name was duplicated

---

.github/workflows/automation-msgraph-metadata-importer.yaml
.github/workflows/automation-rest-api-specs-importer.yaml
.github/workflows/automation-version-bumper.yaml
.github/workflows/unit-test-rest-api-specs-importer.yaml
.gitmodules
README.md
scripts/automation-generate-and-commit-go-sdk.sh
tools/importer-rest-api-specs/README.md
tools/importer-rest-api-specs/cmd/import.go
tools/importer-rest-api-specs/cmd/validate.go
tools/importer-rest-api-specs/components/parser/parser_test.go
tools/importer-rest-api-specs/main.go
tools/importer-rest-api-specs/pipeline/run_validate_can_parse_data_test.go
tools/version-bumper/README.md
tools/version-bumper/main.go

This matches the Microsoft Graph one, and since we're gonna need to run `git submodule init` we might as well do this now too

refactor: moving the `swagger` submodule to `submodules/rest-api-specs`

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_machinelearning_25142.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go

a workaound for https://github.com/Azure/azure-rest-api-specs/issues/25119 also fix https://github.com/hashicorp/pandora/issues/2889

tools/importer-rest-api-specs: adding a workaround for machine learning registry

---

tools/generator-go-sdk/generator/templater_models.go
tools/generator-go-sdk/generator/templater_models_discriminators_test.go

This PR fixes https://github.com/hashicorp/go-azure-sdk/issues/287 by exposing the Raw types rather than using internal types for these.
Since these fields are intentionally only consumable via the Response and are not usable in Request Payloads exposing this is reasonable, but I've added a warning that these should be a last resort/workaround only.

tools/generator-go-sdk: exporting the Raw generated types

---

tools/importer-rest-api-specs/components/parser/resourceids/common_id_storage_account.go
tools/importer-rest-api-specs/components/parser/resourceids/common_id_storage_container.go
tools/importer-rest-api-specs/components/parser/resourceids/common_ids.go

Dependent on https://github.com/hashicorp/go-azure-helpers/pull/173
Fixes #2875

tools/importer-rest-api-specs: adding Common ID for Storage Account and Storage Container

---

tools/generator-go-sdk/main.go

Possible now that https://github.com/hashicorp/pandora/issues/2825 has been fixed

data: moving `DevTestLabs` over to the new base layer

---

config/resource-manager.hcl

Support new service `ChaosStudio`. 
Swagger: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/chaos/resource-manager/Microsoft.Chaos/preview/2023-04-15-preview

Config : adding `ChaosStudio` @ `2023-04-15-preview` 

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_automation_25435.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go

add a workaround for https://github.com/Azure/azure-rest-api-specs/pull/25435

`automation`:add new workaround for automation python3package lro

---

tools/generator-go-sdk/main.go

Github bug didn't pick up the changes pushed to this branch - this has been previously reviewed here: https://github.com/hashicorp/pandora/pull/2456#issuecomment-1693155912

tools/generator-go-sdk: updating keyvault to use the new base layer

---

tools/generator-go-sdk/main.go

Postponing this switch for now

tools/generator-go-sdk: reverting `KeyVault` to the old base layer for the moment

---

tools/importer-rest-api-specs/components/parser/resourceids/generate_names.go

fix #1509
for these resource ids with the same length, the old sort logic will cause unstable result like below. this PR try to compare the uri itself to fix the EC issue.

`importer`: fix sort uri logic `generateNamesForResourceIds` which may cause eventual consistency

---

tools/importer-rest-api-specs/components/parser/models_test.go
tools/importer-rest-api-specs/components/parser/parser.go
tools/importer-rest-api-specs/components/parser/testdata/operations_multiple_with_stuttering.json

When all Operations within a API Resource begin with the same prefix, and that prefix is the API Resource name, we can trim the API Resource from the name of each Operation to simplify this. This means that for example `AlertProcessingRulesCreateOrUpdate` within the `AlertProcessingRules` package becomes `CreateOrUpdate`.
This simplifies these callers, and since this only occurs when all operations contain the prefix, there can't be any conflicting operations.
This scenario happens when the Swagger Tag contains spaces and differs from the prefix used for the Operation ID (e.g. a Swagger Tag of `Example Value` with an OperationID of `ExampleValue_SomeOperation`)

`tools/importer-rest-api-specs`: simplifying the Operation names if possible

---

tools/importer-rest-api-specs/components/parser/models_test.go
tools/importer-rest-api-specs/components/parser/parser.go
tools/importer-rest-api-specs/components/parser/testdata/operations_multiple_with_stuttering.json

Fixes https://github.com/hashicorp/pandora/pull/3016#pullrequestreview-1612987765

tools/importer-rest-api-specs: fixing a bug where operation names may start with a rogue `s`

---

config/resource-manager.hcl

`defender for storage` is only avaiable on this version. And it will be consistent with the stable version.

add `security@2022-12-01-preview`

---

config/resource-manager.hcl

These can be removed once https://github.com/hashicorp/terraform-provider-azurerm/pull/23060 has been merged

cleanup: removing older API Versions for `DataProtection`, `DigitalTwins` and `Network`

---

.github/workflows/automation-regenerate-go-sdk.yaml
.github/workflows/automation-regenerate-terraform.yaml

Whilst `xl` exists, `l` doesn't exist for `large`.
Unblocks https://github.com/hashicorp/pandora/actions/runs/6247014090
Unblocks https://github.com/hashicorp/pandora/actions/runs/6247014093

github actions: `l` -> `large`

---

tools/importer-rest-api-specs/components/parser/cleanup/cleanup.go

bug: `listkeys` should be normalized into `listKeys`

---

tools/importer-rest-api-specs/components/parser/models.go
tools/importer-rest-api-specs/components/parser/models_test.go
tools/importer-rest-api-specs/components/parser/operations.go
tools/importer-rest-api-specs/components/parser/testdata/models_bug_2675_duplicate_model.json

should fix the importer issue of #2675. also cherry-picked @tombuildsstuff 's commit of adding Unit Test for it: https://github.com/hashicorp/pandora/commit/d2ea0bbda48287bccd3aa705a7832879ae8b9542
```
--- PASS: TestParseModelBug2675DuplicateModel (0.02s)
PASS
```
I have regenerated all services and it caused no different from main branch's data, (except the DevCenter service):

`tools/importer`: skip build model if input schema is only for property

---

tools/importer-rest-api-specs/components/parser/cleanup/cleanup.go

Fixes CosmosDB in https://github.com/hashicorp/pandora/pull/3096/files#diff-303d1d97a2359c956e7b5ccf32ffefe5711fecfccac9439b7c43b1a38b32597dR40

tools/importer-rest-api-specs: removing `;` and `\r` and `\n` from constant names

---

config/resource-manager.hcl

Onboarding Azure DevCenter. 
Swagger: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/devcenter/resource-manager/Microsoft.DevCenter/stable/2023-04-01

`DevCenter` @ `2022-04-01`

---

config/resources/devcenter.hcl

This PR generates `azurerm_dev_center` and `azurerm_dev_center_project`
Dependent on https://github.com/hashicorp/terraform-provider-azurerm/pull/23530
Supersedes https://github.com/hashicorp/terraform-provider-azurerm/pull/23522

config: generating `dev_center` and `dev_center_project`

---

config/resources/devcenter.hcl
tools/importer-rest-api-specs/components/schema/processors/field_name_max_to_maximum.go
tools/importer-rest-api-specs/components/schema/processors/field_name_max_to_maximum_test.go
tools/importer-rest-api-specs/components/schema/processors/fields.go

Fixes https://github.com/hashicorp/terraform-provider-azurerm/pull/23538#discussion_r1357091497

devcenter: updating `Max` to `Maximum` and updating the website category

---

scripts/automation-generate-and-commit-terraform.sh

This allows the `hashicorp/terraform-provider-azurerm` repository to differentiate between Pandora and Go SDK PRs
x-ref: https://github.com/hashicorp/terraform-provider-azurerm/pull/23565

scripts: updating the Terraform automation to use `auto-pandora-pr` rather than `auto-pr`

---

config/resource-manager.hcl

Swagger : https://github.com/Azure/azure-rest-api-specs/blob/main/specification/redisenterprise/resource-manager/Microsoft.Cache/preview/2023-10-01-preview/redisenterprise.json
Although this is a preview release, the service team has promised that there won't be any breaking changes.

config : adding API Versions for Redis Enterprise

---

tools/importer-rest-api-specs/components/parser/cleanup/cleanup.go

Fixes https://github.com/hashicorp/pandora/pull/3209

tools/importer-rest-api-specs: fixing the segment `datareferences` to `dataReferences` for MachineLearningWorkspaces

---

tools/data-api/internal/endpoints/home_page.go
tools/data-api/internal/endpoints/routing.go

A minor nit, but I keep referring to this page - and it's fallen out of sync, so making this dynamic means we don't have to update it but it remains useful.

`tools/data-api`: updating the list of home page routes to be dynamic

---

config/resource-manager.hcl

it's required by new feature. and the service team committed this preview version will be GA version

add `Authorization@2022-05-01-preview`

---

api-definitions/README.md
tools/importer-rest-api-specs/components/dataapigeneratorjson/generate_api_versions.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/generate_package.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/helpers.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/interface.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/models/models.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/models/object_definition.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_models.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_operations.go
tools/importer-rest-api-specs/main.go
tools/importer-rest-api-specs/pipeline/run_importer.go
tools/importer-rest-api-specs/pipeline/task_generate_data_api_definitions_v2.go

This PR refactors the V2 API Definitions for Models/Fields/Object Definitions - such that:
* Updates the structs for Models, Field (now `ModelField`, to differentiate it from a Terraform Schema Field) and ObjectDefinition to fix issues outlined in https://github.com/hashicorp/pandora/pull/3185 (and spotted whilst passing through0
* A working directory is assumed to exist at `./api-definitions` - as such `importer-rest-api-specs` can rely on this existing and generate a `resource-manager` directory within it.
* Removes the `namespace` fields used within V2 of the API Definitions (since this is specific to V1)
---
There's one change to V2 of the API Definitions which doesn't exist in V1 worth mentioning, which is that the fields `MaxItems`, `MinItems` and `DateFormat` are now housed within …

`tools/importer-rest-api-specs`: refactoring the V2 API Definitions for Models/Fields/Object Definitions

---

tools/importer-rest-api-specs/components/dataapigeneratorjson/models/constants.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/models/metadata.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/revision_id.go

Given the conventions in JSON, we should conform to this - the side-effect is this gives us an easy tell for models which have been reviewed/refactored verses those which haven't.
This PR also splits out a struct for `MetaData`, since we'll want to reuse this for both ARM, MS Graph and handwritten data - and honestly could make sense for us to serve from the Data API (for example, allowing the new differ tool to output a `compare` link, to show differences in the source data) - so splitting this out into a dedicated struct seems worthwhile.

tools/importer-rest-api-specs: updating the v2 models to use camelCase

---

tools/importer-rest-api-specs/components/dataapigeneratorjson/generate_package.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/models/resource_ids.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_resource_id.go

This PR splits out the Resource ID model, adds missing fields (Constant Name) and documents each of the fields/expected values.
Notably this PR updates the Resource ID types to match those we're expecting in the Data API - with the `Value` field for a Resource ID segment is used as the literal/fixed/required value - rather than being reused for a Constant - which means this'll be nil/unset for other scenarios (as we're expecting).

tools/importer-rest-api-specs: updating the Resource ID models

---

tools/importer-rest-api-specs/components/dataapigeneratorjson/generate_package.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/models/object_definition.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/models/operations.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/models/options_object_definition.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_operations.go

I have a few todos to track down:
```
if operation.ResponseObject != nil {
responseObject.ReferenceName = operation.ResponseObject.ReferenceName
responseObject.Type = operationModels.ObjectDefinitionType(operation.ResponseObject.Type)
// TODO
//if operation.FieldContainingPaginationDetails == nil {
//	code = append(code, fmt.Sprintf(`		public override Type? ResponseObject() => typeof(%[1]s);`, *responseOperationTypeName))
//} else {
//	code = append(code, fmt.Sprintf(`		public override Type NestedItemType() => typeof(%[1]s);`, *responseOperationTypeName))
//}
}
```
```
if operation.FieldContainingPaginationDetails != nil {
HTTPMethod = "List"
// TODO is there a todo here?
// since this is a List operation we need to additionally output the HttpMethod
// since it's possible that these are …
```

`tools/importer-rest-api-specs`: refactoring the Operation models within the `dataapigeneratorjson` package into a `models` directory

---

tools/importer-rest-api-specs/components/dataapigeneratorjson/models/api_version_definition.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/models/metadata.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/revision_id.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_api_version_definition.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_models.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_operations.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_resource_id.go

This PR adds the fields `SourceData` and `SourceInformation` to the `metadata` file, allowing for multiple data sources (i.e. directories, `resource-manager` for generated and `handwritten-resource-manager` for handwritten) to provide Data for a single Service (e.g. AzureResourceManager/MicrosoftGraph) - so that the Data API can be configured to load this.
This also fixes a couple of other bugs spotted when generating the full data set:
* Operations - `ContentType` and `ExpectedStatusCodes` must always be output (the Go SDK generator assumes both are returned from the Data API, and these default values previously came from the base types in C#)
* Operations - `ResourceIdName` and `UriSuffix` are now pointers rather than empty strings, both generators rely on these being nil when omitted …

tools/importer-rest-api-specs: updating the `metadata` file to include the SourceData and SourceInformation

---

tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_operations.go

See #3279 as to why, but example changes from this PR:
```diff
diff --git a/api-definitions/resource-manager/Workloads/2023-04-01/Monitors/Operation-Delete.json b/api-definitions/resource-manager/Workloads/2023-04-01/Monitors/Operation-Delete.json
index 3991fb0ac5..5231d803ae 100644
--- a/api-definitions/resource-manager/Workloads/2023-04-01/Monitors/Operation-Delete.json
+++ b/api-definitions/resource-manager/Workloads/2023-04-01/Monitors/Operation-Delete.json
@@ -2,9 +2,9 @@
"name": "Delete",
"contentType": "application/json",
"expectedStatusCodes": [
-  204,
200,
-  202
+  202,
+  204
],
"longRunning": true,
"httpMethod": "DELETE",
diff --git a/api-definitions/resource-manager/Workloads/2023-04-01/ProviderInstances/Operation-Delete.json …
```

tools/importer-rest-api-specs: sorting the `expectedStatusCodes` property to remove eventual consistency issues

---

tools/importer-rest-api-specs/components/parser/resourceids/common_id_sql_database.go
tools/importer-rest-api-specs/components/parser/resourceids/common_id_sql_elastic_pool.go
tools/importer-rest-api-specs/components/parser/resourceids/common_id_sql_managed_instance.go
tools/importer-rest-api-specs/components/parser/resourceids/common_id_sql_managed_instance_database.go
tools/importer-rest-api-specs/components/parser/resourceids/common_id_sql_server.go
tools/importer-rest-api-specs/components/parser/resourceids/common_ids.go

Adds SqlDatabase, SqlElasticPool, SqlManagedInstanceDatabase, SqlManagedInstance and SqlServer
Dependent on https://github.com/hashicorp/go-azure-helpers/pull/193

tools/importer-rest-api-specs: New Common IDs for SQL

---

.github/workflows/automation-msgraph-metadata-importer.yaml
.github/workflows/automation-regenerate-go-sdk.yaml
.github/workflows/automation-regenerate-terraform.yaml
.github/workflows/automation-rest-api-specs-importer.yaml
.github/workflows/automation-version-bumper.yaml

This allows us to force these from `main` in the event of a Github Actions outage, as I believe could be in progress (the GHA's didn't get picked up for #3288, but should have done?)

Github: Adding a Run button

---

tools/data-api/internal/endpoints/v1/mappings.go
tools/data-api/internal/repositories/models.go
tools/data-api/internal/repositories/models/models.go
tools/data-api/internal/repositories/services.go
tools/data-api/internal/repositories/validation.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/models/models.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_models.go

When loading and parsing the data we now just map everything from the data definitions over into the data api models 1:1, then do additional validation around discriminators when we validate object definitions etc.
This will also include various fixes to the data that's output in the data API. See individual commits.

Data API V2: thread through `TypeHintIn`, `Description` and add validation around discriminators

---

tools/data-api/internal/endpoints/v1/schema_for_api_resource.go
tools/data-api/internal/repositories/services.go
tools/data-api/models/api_schema_details.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_operations.go

The mapped fields from the data definitions weren't being set correctly.
Also exposing the `ParentTypeName` in the v1 endpoint and removed `Default` in the v1 endpoint since this is not used.

Data API V2: set fields correctly back into model and various fixes/cleanup

---

tools/importer-rest-api-specs/components/parser/cleanup/cleanup.go

Fixes https://github.com/hashicorp/pandora/issues/3050

`tools/importer-rest-api-specs`: normalizing `runAsAccount` to remove an eventual consistency issue

---

.github/workflows/automation-extract-tf-resource-ids.yaml
.github/workflows/automation-regenerate-go-sdk.yaml
.github/workflows/automation-regenerate-terraform.yaml

This works around a limitation where GHA only triggers based on the first 3000 files in a given changeset, which may or may not contain `./data`. Since API Definitions are temporarily output to both `./api-definitions` and `./data` - this PR means we trigger on both regardless, working around this issue for the moment.

automation: running the automation when `./api-definitions` changes

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_recoveryservicessiterecovery_26680.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go

This is currently hand-defined in the Provider https://github.com/hashicorp/terraform-provider-azurerm/blob/bf4b436d9bd36ee253c4947f4812846528a47345/internal/services/recoveryservices/azuresdkhacks/model_certificaterequest.go#L12-L19 and should instead be added to the API Definition
x-link: https://github.com/Azure/azure-rest-api-specs/pull/26680

`tools/importer-rest-api-specs`: adding a workaround for Azure/azure-rest-api-specs PR 26680

---

tools/data-api/go.mod
tools/data-api/go.sum

This ensures that these are sourced from the local disk rather than an untagged revision - to match the other tooling.
ctx: https://github.com/hashicorp/pandora/pull/3382/files#diff-cc49cf4a51c8b072add49b7bf868102dfa5d7601027382d31522f4bdf33ca59aR10

tools/data-api: using a go mod replace to find the sdk

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_hdinsight_26838.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go

Works around https://github.com/Azure/azure-rest-api-specs/pull/26838

tools/importer-rest-api-specs: adding a workaround for HDInsight 26838

---

tools/data-api/internal/endpoints/routing.go
tools/data-api/internal/repositories/discovery.go
tools/data-api/internal/repositories/mappings.go
tools/data-api/internal/repositories/models.go
tools/data-api/internal/repositories/services.go
tools/data-api/models/service_detail.go

Closes #3277
Closes #3411
**Summary:**
- `NewServicesRepository` has been updated to do the following:
- Auto discovers subdirectories in the root dir of the api definitions with a `metadata.json`
- Checks the DataSource specified in the `metadata.json` and builds a complete list of services for a given service type that populates the new attribute `serviceDirectory` which maps the service to a filepath
- Validates that there aren't duplicate definitions for a service across several directories
- Returns errors
- Updated the paths we use when loading the definitions to use the information stored in the new attribute `serviceDirectory`
- The entry point into the server/root routing handles the error for `NewServicesRepository` and exits if there is one
- `ServiceDefinition.json` is being …

Data API V2: extending `NewServicesRepository` to build a complete list of services

---

.github/workflows/unit-test-data-api-v2.yaml
tools/data-api/GNUmakefile
tools/data-api/internal/endpoints/v1/mappings.go
tools/data-api/internal/repositories/services_test.go
tools/data-api/internal/repositories/validation.go

dataapiv2 - Add github actions to dataapiv2

---

.github/workflows/automation-regenerate-go-sdk.yaml
scripts/automation-generate-and-commit-go-sdk.sh

This PR flips the flag from `false` to `true` for the go sdk generation.
The script `automation-generate-and-commit-go-sdk.sh` was executed locally and ran successfully with no diffs.

Data API V2: use data api v2 to generate `go-azure-sdk`

---

config/resource-manager.hcl

This version was pulled https://github.com/Azure/azure-rest-api-specs/commit/60679ee3db06e93eb73faa0587fed93ed843d6dc
And is causing https://github.com/hashicorp/pandora/pull/3465 to fail.

config - remove `dataprotection` `2023-08-01` since this was pulled in the Rest API Specs repo

---

tools/importer-rest-api-specs/components/parser/resourceids/common_id_hdinsight_cluster.go
tools/importer-rest-api-specs/components/parser/resourceids/common_ids.go

Dependent on https://github.com/hashicorp/go-azure-helpers/pull/198

tools/importer-rest-api-specs: HDInsight Cluster is now a Common ID

---

tools/data-api/internal/endpoints/v1/terraform.go
tools/data-api/internal/endpoints/v1/terraform_mappings.go
tools/data-api/internal/repositories/helpers.go
tools/data-api/internal/repositories/services.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_terraform_mappings.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_terraform_schema.go

This PR should be the last of the Terraform fixes needed for the terraform generation to be 1-1. 
There is one issue in that the ordering of ModelToModel mappings does not match the old data api model. This will cause differences when running the generator but it should only happen once. I don't see a way to get the ordering to match but if we really want 1-1 then it will require another set of eyes to figure it out

dataapiv2: More terraform v2 fixes

---

config/resource-manager.hcl

missed by https://github.com/hashicorp/pandora/pull/3477
authorization@2020-04-01-preview in `azure-sdk-go` is using `2018-01-01-preview` for `roleDefinitions`...
```
input-file:
- Microsoft.Authorization/preview/2015-06-01/authorization-ClassicAdminCalls.json
- Microsoft.Authorization/stable/2015-07-01/authorization-ElevateAccessCalls.json
- Microsoft.Authorization/preview/2018-01-01-preview/authorization-ProviderOperationsCalls.json
- Microsoft.Authorization/preview/2018-01-01-preview/authorization-RoleDefinitionsCalls.json
- Microsoft.Authorization/preview/2018-07-01-preview/authorization-DenyAssignmentGetCalls.json
- Microsoft.Authorization/preview/2019-08-01-preview/authorization-UsageMetricsCalls.json
- Microsoft.Authorization/preview/2020-04-01-preview/authorization-RoleAssignmentsC …
```

add authorization_2018-01-01-preview

---

.gitignore
scripts/automation-determine-changes-to-api-definitions.sh

The Github Actions agents aren't setting `$TMPPATH` so let's just output this into `./pandora-from-main` for now

automation: fixing the checkout path

---

.github/workflows/automation-data-api-differ.yaml
scripts/automation-determine-changes-to-api-definitions.sh

Copied this from the wrong GHA - right now this runs from `main` against `main` which means [no changes are output](https://github.com/hashicorp/pandora/pull/3500#issuecomment-1857602479) - this fixes that.

automation: `data-api-differ` should run against PRs and not the target branch

---

scripts/automation-determine-changes-to-api-definitions.sh

This shouldn't be needed since the GHA is checking out all branches, but hey.

automation: forcing the fetch of `origin/main`

---

config/resource-manager.hcl

To fix https://github.com/hashicorp/terraform-provider-azurerm/issues/13066 I'd like to have the latest API version for ContainerService!
Thanks a lot!
If it is preferred to have an old preview version (to support some preview features) it might be that #3469 is the right one to merge, but I'm not completely up to speed with these kind of things 🧪

Add `ContainerService/2023-10-01`

---

tools/data-api-differ/internal/commands/detect_breaking_changes.go
tools/data-api-differ/internal/commands/detect_changes.go
tools/data-api-differ/internal/commands/output_resource_id_segments.go
tools/data-api-differ/internal/differ/differ.go
tools/data-api-differ/internal/differ/differ_api_resource.go
tools/data-api-differ/internal/differ/differ_api_resource_test.go
tools/data-api-differ/internal/differ/differ_api_versions.go
tools/data-api-differ/internal/differ/differ_api_versions_test.go
tools/data-api-differ/internal/differ/differ_helpers_test.go
tools/data-api-differ/internal/differ/differ_services.go
tools/data-api-differ/internal/differ/differ_services_test.go
tools/data-api-differ/internal/differ/interface.go

When diffing the changes in https://github.com/hashicorp/pandora/pull/3570 the Data API Differ has correctly identified the changes however the list of changes is too long to render in a single Github comment, meaning that the Github Action currently fails for new Data PRs.
Whilst we're planning to change how this output is rendered which'll fix the issue in the medium-term - this PR updates the currently rendered output such that when a new API Resource is detected that we'll skip outputting the list of nested changes (e.g. the full set of Constants/Models/Resource IDs) in the structured output.
This means that the "Non Breaking Changes" present in #3570 gets reduced from 6420 lines to this:
```markdown
**185 Non-Breaking Changes** were detected:
* ✅ **New API Version:** `2023-12-01` in …
```

`tools/data-api-differ`: shortening the list of changes when a new API Resource is detected

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_operationalinsights_26678.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go

adding workaround for https://github.com/hashicorp/go-azure-sdk/issues/735 ( https://github.com/Azure/azure-rest-api-specs/issues/26678 )
will convert to ready to review once the test pipeline pass

add workaround for #26678

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_operationalinsights_26678.go

This should be set back into `Clusters` and not `Cluster`.

nit: `tools/importer-rest-api-specs` - fixing the workaround for 26678 from #3478

---

tools/generator-go-sdk/generator/templater_methods.go
tools/generator-go-sdk/generator/templater_methods_test.go

Fixes https://github.com/hashicorp/go-azure-sdk/issues/716

`tools/generator-go-sdk`: outputting the latest HTTP Response as a part of the `ListComplete` object

---

config/resources/chaosstudio.hcl
config/resources/containerservice.hcl
tools/importer-rest-api-specs/components/resources/identification.go
tools/importer-rest-api-specs/components/schema/builder.go
tools/importer-rest-api-specs/components/schema/internal.go

Currently we skip resource generation if a candidate resource has a scoped resource ID segment. This PR removes that check and flips the logic for setting the Create/Read/Update Property payload instead of erroring.
These changes are required to be able to generate the resource Chaos Studio Targets. This shouldn't result in changes to the existing Data API definitions.

`importer-rest-api-specs` - support resource generation for resources with a scoped ID segment

---

tools/importer-rest-api-specs/components/parser/resourceids/common_id_kusto_cluster.go
tools/importer-rest-api-specs/components/parser/resourceids/common_id_kusto_database.go
tools/importer-rest-api-specs/components/parser/resourceids/common_ids.go

Dependent on https://github.com/hashicorp/go-azure-helpers/pull/186

`tools/importer-rest-api-specs`: New Common IDs for Kusto Cluster and Kusto Database

---

tools/data-api/internal/endpoints/v1/terraform.go
tools/data-api/internal/endpoints/v1/terraform_mappings.go
tools/data-api/internal/repositories/services.go
tools/data-api/internal/repositories/terraform_models.go

This updates the mapping logic so that we return a pointer to a map as the result of the function, rather than a map directly - this allows us to differentiate between unset (e.g. an error has occurred) and when a value exists - which fixes the root cause of https://github.com/hashicorp/pandora/pull/3628 (and means that downstream tooling can avoid nil-checking these)
This PR also adds some additional mappings for the `repository` types to the types used for the API responses rather than string casting - since string casting in Go will map the cast the literal value (which'll always be valid) meaning that we wouldn't necessarily map the value we're defining across.

tools/data-api: fixing the mapping of Terraform specific objects

---

.github/workflows/automation-data-api-differ.yaml

The API definitions aren't changed at this point (but might make sense for us to handle in the end-to-end test) as such I'm disabling this for now since this fails for forked PRs.

automation: disabling `Detect changes to the API Definitions` when `importer-rest-api-specs` changes

---

tools/importer-rest-api-specs/components/parser/constants/interface.go
tools/importer-rest-api-specs/components/parser/constants_test.go
tools/importer-rest-api-specs/components/parser/testdata/constants_integers_with_names.json
tools/importer-rest-api-specs/components/parser/testdata/constants_integers_with_names_inlined.json

This commit fixes https://github.com/hashicorp/pandora/issues/3010 by checking for a Display Name within the `x-ms-enum` block and pulling from that if a (Display) Name is defined for an Integer constant.
Whilst I considered doing this for Float and String constants too, I've intentionally omitted those since Float constants are rare (so we can apply this same fix if needed down the line) - and for String constants there's little benefit to changing at this point, since we normalize a key from the value for the constant.
Ultimately this should ensure that when we import the constant `EmailChannelAuthMethod` for `BotService` that we output this as:
> `Password`: `0`
> `Graph`: `1`
Which is far more descriptive than:
> `Zero`: `0`
> `One`: `1`
---
There's a couple of changes to the existing …

`tools/importer-rest-api-specs`: support for pulling the Display Name for an Integer Constant if defined

---

config/resource-manager.hcl
tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_botservice_27351.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go
tools/importer-rest-api-specs/components/parser/resourceids/common_id_bot_service_channel.go

This PR adds a data workaround for https://github.com/Azure/azure-rest-api-specs/pull/27351 which enables importing `BotService` @ `2022-09-15`.
The Swagger defines the same Path with different types of segments depending on the HTTP Method, where the DELETE and GET operations use a String segment - but the PATCH and POST operations use a Constant segment - meaning that whilst we detect the Common ID (using the Constant segments) it's inconsistent).
Related: https://github.com/hashicorp/go-azure-helpers/pull/203

`tools/importer-rest-api-specs`: adding a data workaround for `Azure/azure-rest-api-specs#27351` / importing `BotService` @ `2022-09-15`

---

tools/generator-go-sdk/generator/templater_methods.go
tools/generator-go-sdk/generator/templater_methods_test.go

This PR fixes an issue in the new base layer where a list of Discriminated Types is returned from a (in this case, List) operation.
This mirrors the behaviour of the old base layer, by creating an intermediate slice to deserialize into, calling `unmarshal` on each of the items.
Fixes https://github.com/hashicorp/pandora/issues/3639
Unblocks https://github.com/hashicorp/terraform-provider-azurerm/pull/24481

`tools/generator-go-sdk`: fixing support for top-level discriminated lists in the new base layer

---

tools/importer-rest-api-specs/components/parser/load_and_parse.go

parity with `dataapiv1` is no longer needed
`web` LRO / List operation responses are required
fixes #2828 
Example Usage:
```go
resp, err := client.SomeLROFunction(ctx, id)
if err != nil {
return err
}
someModel := &service.MyModel{}
if err = resp.Poller.FinalResult(MyModel); err != nil {
return nil, nil, fmt.Errorf("reading Publishing Credential information: %+v", appID, err)
}
```

`importer-rest-api-specs` - remove workaround to remove LRO models 

---

tools/data-api/internal/repositories/mappings.go
tools/data-api/internal/repositories/services.go
tools/importer-rest-api-specs/components/parser/resourceids/common_id_chaos_studio_capability.go
tools/importer-rest-api-specs/components/parser/resourceids/common_id_chaos_studio_target.go
tools/importer-rest-api-specs/components/parser/resourceids/common_ids.go
tools/importer-rest-api-specs/components/testing/attribute_value_for_field.go
tools/importer-rest-api-specs/components/testing/complete.go
tools/importer-rest-api-specs/components/testing/complete_test.go
tools/importer-rest-api-specs/components/testing/dependencies.go

This PR adds a common ID for Chaos Studio Capability and Target and also fixes the swapping out of test data for fields that have been renamed, as well as omits generation of the complete test configuration if all fields are Required.
Dependent on https://github.com/hashicorp/go-azure-sdk/pull/819

commonids - add common IDs for chaos studio capability and target

---

tools/importer-rest-api-specs/components/parser/load_and_parse.go

Reverts hashicorp/pandora#3641
Will fix the issue in the morning, but want to leave the pipeline clean

Revert "`importer-rest-api-specs` - remove workaround to remove LRO models "

---

tools/data-api/internal/endpoints/routing.go
tools/data-api/internal/repositories/models.go
tools/data-api/internal/repositories/services.go
tools/data-api/internal/repositories/services_test.go
tools/sdk/resourcemanager/client.go

Chatting with @manicminer - rather than having two separate Data Sources for `Beta` and `Stable V1` for Microsoft Graph, we're going to try and use the same versioning approach that Resource Manager does - that is `/v1/{DataSourceType}/{ServiceName}/{ApiVersion}/{ApiResource}` - e.g. `/v1/microsoft-graph/Applications/{beta|v1stable}/Application`.
As such this PR:
1. Consolidates `/v1/microsoft-graph/beta` and `/v1/microsoft-graph/stable-v1` into `/microsoft-graph`.
2. Updates the constants to reflect this.
3. Removes the unused `/infrastructure` endpoint (the SDK uses `/v1/health` rather than `/infrastructure/health`, so this is fine)

`tools/data-api`: consolidating the `microsoft-graph` endpoints together

---

config/resource-manager.hcl

To onboard Arc VM on Azure Stack HCI, related doc can be found at [Create Arc virtual machines on Azure Stack HCI (preview)](https://learn.microsoft.com/en-us/azure-stack/hci/manage/create-arc-virtual-machines?tabs=azurecli)
The `2023-09-01-preview` is confirmed has no breaking changes in the future.
swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/azurestackhci/resource-manager/Microsoft.AzureStackHCI/preview/2023-09-01-preview/virtualMachineInstances.json

Config: Add `Microsoft.AzureStackHCI@2023-09-01-preview`

---

tools/generator-go-sdk/main.go
tools/generator-terraform/generator/definitions/template_service_client.go
tools/generator-terraform/generator/definitions/template_service_client_test.go

This also requires updating `generator-terraform` to account to account for that.
However - given these updates need to be coordinated - merging this change will (temporarily) break the `generator-terraform` automation, as the resulting code won't compile. This is because the SDK version vendored into `hashicorp/terraform-provider-azurerm` still uses the old base layer, as such the Go SDK will need to be released and then updated in `hashicorp/terraform-provider-azurerm` by hand - at which point the automation will work as usual.
Whilst it's possible to stagger the updates such that we released the Go SDK switching these two services over to the new base layer, and then did the same for the Terraform Provider - the end result is the same insofar as we'd end up needing to manually …

`tools/generator-go-sdk`: updating `LoadTestService` and `ManagedIdentity` to use the new base layer

---

tools/importer-rest-api-specs/components/parser/load_and_parse.go

This commit reimplements https://github.com/hashicorp/pandora/pull/3641 which surfaces the Response Object for Long Running Operations
Dependent on #3664

`tools/importer-rest-api-specs`: surfacing the Response Object for Long Running Operations

---

config/resource-manager.hcl
tools/generator-go-sdk/main.go

This PR:
* Removes the now unused API Versions `2021-10-01` and `2022-11-01` for `KeyVault`
* Updates `KeyVault` API Version `2023-07-01` to use the new base layer
---
In creating an up-to-date repro for the Key Vault Constant casing issues, it appears that `2023-07-01` doesn't contain these issues - and whilst it's possible that earlier versions have been fixed - for the sake of a migration path this PR intentionally leaves `2023-02-01` on the older base layer - whilst allowing us a path to fixing some of the other open issues such as https://github.com/hashicorp/terraform-provider-azurerm/pull/24449

`keyvault`: `2023-07-01` uses the new base layer / removing unused API Versions

---

config/resources/chaosstudio.hcl
docs/resource-manager-generate-new-resource.md
docs/resource-manager-partial-resource-generation.md

This PR adds the resource definition for Chaos Studio Target which will be a partially generated resource. 
This is dependent on https://github.com/hashicorp/terraform-provider-azurerm/pull/24580

config - add Chaos Studio Target resource definition

---

config/resource-manager.hcl

This PR removes older API versions which are no longer used in `hashicorp/terraform-provider-azurerm`.

`config`: removing unused older API Versions

---

config/resource-manager.hcl

These two are still needed:
```
$ go get github.com/hashicorp/go-azure-sdk@v0.20240124.1094959                                                                                                                                                   (dependencies/go-azure-sdk)
go: downloading github.com/hashicorp/go-azure-sdk v0.20240124.1094959
go: upgraded github.com/hashicorp/go-azure-sdk v0.20240122.1074123 => v0.20240124.1094959
11:01AM hashicorp/terraform-provider-azurerm
$ go mod tidy
go: finding module for package github.com/hashicorp/go-azure-sdk/resource-manager/cosmosdb/2022-05-15/cosmosdb
go: finding module for package github.com/hashicorp/go-azure-sdk/resource-manager/cosmosdb/2022-11-15/mongorbacs
go: finding module for package …
```

config: adding back in two versions of CosmosDB

---

.copywrite.hcl

As a part of going through the open PRs to see what's mergeable/closed - this PR adds the copywrite configuration needed to enable copywrite to be used in the future.
This allows closing the PR https://github.com/hashicorp/pandora/pull/2117 which has been parked for ages - but should finally be actionable once https://github.com/hashicorp/pandora/issues/3583 is completed (and the old Data API is removed).

nit: adding the `copywrite` configuration

---

scripts/automation-generate-and-commit-go-sdk.sh

This ensures that if a new import path is included in the generated code, it's marked as a dependency in the `go.mod`
Note: this script is only run in Github Actions since it commits and pushed the branch

automation: dependencies are now updated within the `resource-manager` Go module after generation

---

tools/importer-rest-api-specs/components/parser/internal/helpers.go
tools/importer-rest-api-specs/components/parser/swagger_tags.go

This PR unblocks migrating the `Tags` client from `Azure/azure-sdk-for-go` to `hashicorp/go-azure-sdk` as used here: https://github.com/hashicorp/terraform-provider-azurerm/blob/75182167d45fbfd0d68b0c9e9ce6340496276f0b/internal/services/resource/client/client.go#L121-L126
We're currently skipping importing both the `AzureFirewallFqdnTags` and the Consumption tags - taking a quick look at the generated output for both I'm not necessarily sure we should be supporting these, so I've added exceptions for these back in for the moment.

`tools/importer-rest-api-specs`: support for importing `Resources/*/Tags`

---

tools/importer-rest-api-specs/components/parser/models.go
tools/importer-rest-api-specs/components/parser/models_test.go
tools/importer-rest-api-specs/components/parser/testdata/model_inheriting_from_other_model_with_only_description.json

`AllOf` is intended to be a reference, however sometimes can contain a description instead.

`tools/importer-rest-api-specs`: supporting `AllOf` containing only a description

---

config/resource-manager.hcl
tools/importer-rest-api-specs/components/parser/resourceids/parse_segments.go

As @wuxu92 has mentioned in #2848, it appears that the issue blocking `HybridAKS` has been resolved - however we also need to detect the segments `connectedClusterResourceUri` and `customLocationResourceUri` as scope's.
As such this PR adds support for `HybridAzureKubernetesService` (which is intentionally spelled out since we also have `HybridKubernetes`) @ `2024-01-01`.

`hybridaks`: importing API Version `2024-01-01`

---

tools/importer-rest-api-specs/components/parser/models.go
tools/importer-rest-api-specs/components/parser/models_discriminators_test.go
tools/importer-rest-api-specs/components/parser/parse_data.go
tools/importer-rest-api-specs/components/parser/parser.go
tools/importer-rest-api-specs/components/parser/swagger_resources.go
tools/importer-rest-api-specs/components/parser/testdata/nestedtestdata/model_discriminators_orphaned_child.json
tools/importer-rest-api-specs/components/parser/testdata/nestedtestdata/model_discriminators_orphaned_child_with_nested_model.json

This PR closes #3693 and is related to #2551 but doesn't close it since we skip over this new functionality for DataFactory due to #3725.
Although we iterate over files in a nested directory structure, if the files have no paths defined then we don't parse any of the models defined in them. 
This change adds the following functionality:
- Will find all discriminated models in files without any paths
- Find any models that the discriminated models reference
- Combine them into the resource they belong to (this depends on the file name, ChaosStudio and DataFactory use the resource name as the file name)
- Links the discriminated models to the parent, updating the data on the model that describes it as a discriminator 
Note: `DataMigration` and `SecurityInsights` are also affected by this …

`importer-rest-api-specs` - parse orphaned discriminated models in nested files

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_streamanalytics_27577.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go

This fixes an issue where `streamanalytics` defines it's own identity types.

`tools/importer-rest-api-specs`: adding a workaround covering Azure/azure-rest-api-specs#27577

---

tools/generator-go-sdk/generator/templater_readme.go
tools/generator-go-sdk/generator/templater_readme_test.go

This PR fixes an issue where the README's for each SDK within the Go SDK didn't take into account Common IDs - meaning that [the readme's on `pkg.go.dev`, such as this one](https://pkg.go.dev/github.com/hashicorp/go-azure-sdk/resource-manager@v0.20240131.1195211/managementgroups/2020-05-01/managementgroups#section-readme) aren't correct.
Fixes #2951

`tools/generator-go-sdk`: outputting the Common IDs in the READMEs when a Common ID is used in an operation

---

tools/data-api/internal/endpoints/home_page.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_resource_id.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_terraform_resource_definition.go
tools/importer-rest-api-specs/components/discovery/data.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_hdinsight_26838.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_streamanalytics_27577.go
tools/importer-rest-api-specs/components/parser/helpers_test.go
tools/importer-rest-api-specs/components/parser/operations_test.go
tools/importer-rest-api-specs/components/parser/parse_data.go
tools/importer-rest-api-specs/components/parser/resourceids/common_ids.go
tools/importer-rest-api-specs/components/schema/builder.go
tools/importer-rest-api-specs/pipeline/interface.go

This PR introduces a test assertion helper for the Swagger Parser - the intention being to allow defining the object we're expecting rather than checking specific fields - which should reduce the size of (most of) these tests. It also has the benefit of centralising these assertions, which'll make the upcoming refactoring work in `importer-rest-api-specs` easier.
In this PR I've intentionally only switched over a couple of tests to using this for now, given the number of tests (~150) this wants doing piecemeal to make reviewing easier.

`tools/importer-rest-api-specs`: adding a test assertion helper for the Swagger Parser

---

tools/generator-go-sdk/main.go
tools/generator-terraform/generator/definitions/template_service_client.go
tools/generator-terraform/generator/definitions/template_service_client_test.go

This PR removes support for using SDK Clients using the old base layer from `./tools/generator-terraform` - since once #3742 has been merged, all (existing) generated resources will be exclusively using the new base layer. Any newly generated resources should be using the new base layer from the start at this point - so this should be fine to remove.
> **Note:** this doesn't remove support for the old base layer from `./tools/generator-go-sdk` since [this is still needed at this time](https://github.com/hashicorp/pandora/blob/356b3c415d30b6fcdac6600fa063d04695349082/tools/generator-go-sdk/main.go#L30-L69).
Dependent on #3742

`tools/generator-terraform`: removing support for the old base layer

---

tools/importer-rest-api-specs/components/parser/helpers_test.go
tools/importer-rest-api-specs/components/parser/operations_test.go
tools/importer-rest-api-specs/components/parser/resource_ids_test.go
tools/importer-rest-api-specs/components/parser/swagger_tags_test.go
tools/importer-rest-api-specs/components/parser/temp_removed_after_sdk_migration.go
tools/importer-rest-api-specs/components/parser/testdata/operation_content_types.json
tools/importer-rest-api-specs/components/parser/testdata/operations_single_returning_a_list_of_list_of_model.json
tools/importer-rest-api-specs/components/parser/testdata/operations_single_returning_a_list_of_model.json
tools/importer-rest-api-specs/components/parser/testdata/operations_single_returning_a_top_level_raw_object.json
tools/importer-rest-api-specs/components/parser/testdata/operations_single_with_querystring_options.json

This PR updates some of the Swagger Parser tests over to using the new test helper tooling - which'll make refactoring this project over to using the new Data API SDK types easier in the future (and has the side-benefit of halving the amount of code needed per test).
Given the number of tests which need to be converted over I've opted to split this PR in two - with `constants` and `models` still to go.
Part of #3754

`tools/importer-rest-api-specs`: updating (half) the tests to use the new test assertion helpers

---

tools/generator-go-sdk/main.go
tools/wrapper-automation/internal/pipeline/go_sdk_generator.go

I'd checked the scripts for these but apparently forgotten to enable this in the automation codebase itself now that https://github.com/hashicorp/pandora/pull/3802 has been merged 🤦

`tools/wrapper-automation`: applying the same fix to the Go SDK Generator

---

tools/generator-go-sdk/internal/cmd/generate.go

Reimplementing https://github.com/hashicorp/pandora/pull/3809 since there's a merge conflicts and this is quicker
Supersedes https://github.com/hashicorp/pandora/pull/3809

`tools/generator-go-sdk`: `SecurityInsights` now uses the new base layer

---

tools/importer-rest-api-specs/components/dataapigeneratorjson/filesystem.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/stage_models.go
tools/importer-rest-api-specs/components/dataapigeneratorjson/stage_operations.go
tools/importer-rest-api-specs/pipeline/run_importer.go

This PR fixes a couple of bugs in `importer-rest-api-specs` where both the Fields/Operations were being used interchangeably - and the Service directories were being unintentionally created in `./api-definitions` rather than `./api-definitions/{sourceDataType}`

`tools/importer-rest-api-specs`: fixing a couple bugs

---

tools/data-api/internal/repositories/services.go

This'll be fixed shortly, but is a temporary workaround to keep the pipeline green, until the refactoring is completed

`tools/data-api`: using a fake example for the constant example value for now

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_inconsistent_swagger_segments.go
tools/importer-rest-api-specs/components/parser/resourceids/distinct_resource_ids.go

This fixes a regression where the Example Value would flip based on the order the Resource IDs were updated in

`tools/importer-rest-api-specs`: ensuring the Example Value is updated when the Segments are updated

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_devcenter_26189.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_recoveryservicessiterecovery_26680.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_redis_22407.go
tools/importer-rest-api-specs/components/parser/helpers_test.go
tools/importer-rest-api-specs/components/parser/internal/structs.go
tools/importer-rest-api-specs/components/parser/models.go
tools/importer-rest-api-specs/components/parser/models_test.go
tools/importer-rest-api-specs/components/transformer/models_to_api.go
tools/importer-rest-api-specs/models/models.go

These aren't current used but are threaded through in a few places (and should be being used) - so for now I've opted to comment these out with the TODO used as a reference for the issue (which'll be coming when the refactoring is completed)
This enables us to switch out usages of `importerModels.FieldDetails` for `SDKField` far more easily - and then re-enable this once support has been added.

`tools/importer-rest-api-specs`: temporarily disabling the `ReadOnly` and `Sensitive` field values

---

tools/importer-rest-api-specs/components/parser/swagger_resources.go

This PR fixes a regression where PATCH operations would be identified as a List operation

`tools/importer-rest-api-specs`: ensuring that the list operations aren't pulled out for non-GET methods

---

tools/importer-rest-api-specs/components/parser/resourceids/common_ids.go

Whilst this should be enabled, it's hindering fixing the pipeline for the moment - so this PR temporarily disables this until everything is clean. Once thats done, we can update `hashicorp/terraform-provider-azurerm` to account for it.

`tools/importer-rest-api-specs`: temporary disabling the Common ID for Kubernetes Fleet

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_temp_readonly_fields.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go
tools/importer-rest-api-specs/components/parser/helpers_test.go
tools/importer-rest-api-specs/components/parser/models.go

This PR disables `ReadOnly` for now due to issues with the Swagger Parser not correctly identifying these when a model comes from a separate file - but hardcodes this for the User Assigned Identity resource to keep the Terraform Generator happy.
We'll come back and address this/open an issue for this in a bit.

`tools/importer-rest-api-specs`: disabling ReadOnly for now

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_temp_readonly_fields.go

This PR works around an issue described in https://github.com/hashicorp/pandora/issues/3895 where due to an issue when parsing the Swaggers the `ReadOnly` information is inconsistent - meaning that currently when generating Terraform Resources, an issue exists where fields that should be marked as Computed aren't being picked up as such - the results can be seen in https://github.com/hashicorp/terraform-provider-azurerm/pull/25052.
This issue stems from the fact that we now explicitly differentiate values which are `ReadOnly` from those which aren't, since we're now canonically using the `SDKModel` type throughout - meaning that when generating the Terraform Schema for the specified resource we're using the SDKField's `ReadOnly` property to indicate that the associated Terraform Schema …

`tools/importer-rest-api-specs`: flagging fields that are expected to be Computed in the Terraform Schema to be ReadOnly for now

---

tools/importer-rest-api-specs/components/terraform/testing/dependencies_template.go
tools/importer-rest-api-specs/components/terraform/testing/dependencies_template_test.go

To resolve the comments: https://github.com/hashicorp/terraform-provider-azurerm/pull/25010#issuecomment-1977480891

update the test dependency to remove the use of deprecated fields

---

tools/importer-rest-api-specs/components/parser/constants/interface.go
tools/importer-rest-api-specs/components/parser/constants_test.go
tools/importer-rest-api-specs/components/parser/models.go
tools/importer-rest-api-specs/components/parser/operations.go
tools/importer-rest-api-specs/components/parser/parser.go
tools/importer-rest-api-specs/components/parser/resourceids/parse_segments.go
tools/importer-rest-api-specs/components/parser/swagger_resources.go
tools/importer-rest-api-specs/components/parser/testdata/constants_multiple_type_enums.json

This PR updates the `MapConstant` function to take an additional optional argument called `modelName` which will be used to construct a unique constant name for constants named `type` that do not have a unique name defined by `x-ms-enum` in the swagger.
The approach is intentionally scoped to constants called `type` to prevent renames of constants that already have descriptive field names.
Closes #3725

`importer-rest-api-specs` - construct a unique constant name for `type`

---

tools/importer-rest-api-specs/components/parser/models.go

The fix added previously needs to be commented out and more investigation is required into the Data Factory swagger.

`importer-rest-api-specs` - comment out fix temporarily

---

config/resource-manager.hcl

👋 Hello friends, the Azure Packer plugin needs the 2024-03-01 compute library for a newer version of `galleryimageversions` to solve https://github.com/hashicorp/packer-plugin-azure/issues/395

Add compute 2024-03-01

---

tools/importer-rest-api-specs/components/parser/swagger_tags.go

In https://github.com/hashicorp/pandora/pull/3180 we added deployment operations to the tags to ignore list, however the Packer Azure plugin relies on ListDeploymentOperations for builds, so we need that API back to upgrade the plugin to the newest version of the SDK

Unignore deploymentoperations

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_loadtest_20961.go

The Model `LoadTestResourcePatchRequestBody` was removed and replaced with `LoadTestResourceUpdate`
See https://github.com/Azure/azure-rest-api-specs/commit/3e81da30a1358b6ffcbc7ff222aae5f483971d32
Unblocks https://github.com/hashicorp/pandora/pull/4033

`importer-rest-api-specs` - updating model name to `LoadTestResourceUpdate` in workaround

---

tools/importer-rest-api-specs/components/terraform/testing/dependencies_template.go

To fix the following tests:
```
=== RUN   TestAccKubernetesClusterTrustedAccessRoleBinding_basic
=== PAUSE TestAccKubernetesClusterTrustedAccessRoleBinding_basic
=== CONT  TestAccKubernetesClusterTrustedAccessRoleBinding_basic
testcase.go:113: Step 1/2 error: Error running pre-apply refresh: exit status 1
Error: Unsupported block type
on terraform_plugin_test.tf line 79, in resource "azurerm_kubernetes_cluster" "test":
79:   upgrade_settings {
Blocks of type "upgrade_settings" are not expected here.
--- FAIL: TestAccKubernetesClusterTrustedAccessRoleBinding_basic (3.63s)
FAIL
```

`importer-rest-api-specs` - fix aks test template

---

tools/generator-go-sdk/internal/generator/templater_id_parser.go
tools/generator-go-sdk/internal/generator/templater_id_parser_test.go

This add an `init()` func to resource ids which registers them to a list of known ids that can be used for recasing.
dependent on [#221](https://github.com/hashicorp/go-azure-helpers/pull/221)

`tools/generator-go-sdk` - add init() in id generator

---

config/resource-manager.hcl

We're receiving two GA feature requests which require the minimum api-version 2023-09-02-preview.

add containerservice@2023-09-02-preview

---

config/resources/loadtestservice.hcl

With the ongoing refactor, it doesn't seem like we'll get to expanded terraform generation features for some time so I'm hoping we can disable that generation for load test service to get a much requested feature in quickly

loadtestservice: disable terraform generation until we support encryption

---

tools/importer-rest-api-specs/components/terraform/schema/builder.go

This PR comments out a workaround for the LoadTestService that removes the Encryption block from the sdk as it was blocking Terraform generation. 
Depends on #4061
We'll want to add this check back in when we look to re-enable Terraform generation for LoadTest

LoadTestService: comment out the load test encryption check from the builder

---

config/resource-manager.hcl

Adding network 2022-07-01 to facilitate updating the remaining network resources in AzureRM over to `hashicorp/go-azuer-sdk`.
Also removed old versions of services that are no longer in use in the provider to slim down `go-azure-sdk`.

`config` - add `network` `2022-07-01`

---

tools/generator-go-sdk/internal/generator/templater_methods.go
tools/generator-go-sdk/internal/generator/templater_methods_discriminators_test.go
tools/generator-go-sdk/internal/generator/templater_methods_test.go

`generator-go-sdk`: set `LatestHttpResponse` for List method even HTTP responses error

---

tools/importer-rest-api-specs/components/parser/parser.go

Related: https://github.com/Azure/azure-rest-api-specs/pull/29303

`importer-rest-api-specs` - consolidate private link service resources into one

---

config/resource-manager.hcl

Adding apicenter `2024-03-01` and `2024-03-15-preview`.
Required for https://github.com/hashicorp/terraform-provider-azurerm/issues/26200

config: adding apicenter @ `2024-03-01` and `2024-03-15-preview`

---

config/resource-manager.hcl

Add 2023-07-01-preview for cost-management API.
This will allow addressing hashicorp/terraform-provider-azurerm#23747 . According to a sniff of the network inspector while managing Cost Exports in the Azure portal, this is the only API version in existence which contains the `partitionData` and `dataOverwriteBehavior` field for the export properties, and the `dataVersion` for the export dataset configuration, which in turn allows usage of the Exports API to [seed historical data](https://learn.microsoft.com/en-us/azure/cost-management-billing/automate/tutorial-seed-historical-cost-dataset-exports-api) - not possible unless you are using a new enough `dataVersion` according to the portal.

config: adding cost-management @ 2023-07-01-preview

---

tools/data-api-differ/internal/views/markdown.go

Apparently these 3 were missing

`tools/data-api-differ`: supporting Operations Options Added/Changed/Removed

---

tools/data-api-repository/repository/internal/transforms/sdk_field_object_definition.go
tools/importer-rest-api-specs/components/parser/models.go

Whilst this _is_ related to the ObjectDefinition, we'd want to expose the `Get` and `Set` methods that this information generates against the field, rather than the path to the Object Definition, so we should store this there.
Once this is merged there'll be a change to the Source Data, namely:
```diff
diff --git a/api-definitions/resource-manager/AAD/2021-05-01/DomainServices/Model-HealthAlert.json b/api-definitions/resource-manager/AAD/2021-05-01/DomainServices/Model-HealthAlert.json
index 5ff0b0af03..1e8ce1801b 100644
--- a/api-definitions/resource-manager/AAD/2021-05-01/DomainServices/Model-HealthAlert.json
+++ b/api-definitions/resource-manager/AAD/2021-05-01/DomainServices/Model-HealthAlert.json
@@ -29,12 +29,12 @@
},
{
"containsDiscriminatedTypeValue": false,
+      "dateFormat": …
```

`tools/importer-rest-api-specs`: ensuring that DateFormats are stored against the Field and not the ObjectDefinition

---

tools/data-api-differ/internal/dataapi/data_api_cmd.go
tools/data-api-repository/repository/helpers_discovery.go
tools/data-api/internal/commands/args.go
tools/data-api/internal/commands/serve.go
tools/data-api/main.go

When testing this I was running the `data-api` from within `./tools/data-api` and totally missed that we weren't picking up non-default paths 🙃

`tools/data-api`: fixing an issue where the input arguments weren't being picked up/used

---

config/resource-manager.hcl

The Service Team have pulled this version, despite it being Stable - so I guess we're removing support for this.
Works around https://github.com/Azure/azure-rest-api-specs/pull/29441

`hdinsight`: removing `2024-05-01`

---

tools/data-api-differ/internal/changes/common_types_api_version_added.go
tools/data-api-differ/internal/changes/common_types_api_version_removed.go
tools/data-api-differ/internal/changes/common_types_constant_added.go
tools/data-api-differ/internal/changes/common_types_constant_key_value_added.go
tools/data-api-differ/internal/changes/common_types_constant_key_value_changed.go
tools/data-api-differ/internal/changes/common_types_constant_key_value_removed.go
tools/data-api-differ/internal/changes/common_types_constant_removed.go
tools/data-api-differ/internal/changes/common_types_constant_type_changed.go
tools/data-api-differ/internal/changes/common_types_model_added.go
tools/data-api-differ/internal/changes/common_types_model_removed.go
tools/data-api-differ/internal/differ/differ.go
tools/data-api-differ/internal/differ/differ_api_resource.go
tools/data-api-differ/internal/differ/differ_api_versions.go
tools/data-api-differ/internal/differ/differ_common_types.go
tools/data-api-differ/internal/differ/differ_common_types_constants.go
tools/data-api-differ/internal/differ/differ_common_types_constants_test.go
tools/data-api-differ/internal/differ/differ_common_types_models.go
tools/data-api-differ/internal/differ/differ_common_types_models_test.go
tools/data-api-differ/internal/differ/differ_common_types_test.go
tools/data-api-differ/internal/differ/differ_fields.go
tools/data-api-differ/internal/differ/differ_helpers.go
tools/data-api-differ/internal/differ/differ_models.go
tools/data-api-differ/internal/differ/differ_operations.go
tools/data-api-differ/internal/differ/differ_resource_ids.go
tools/data-api-differ/internal/differ/differ_services.go
tools/data-api-differ/internal/views/markdown.go

Fixes https://github.com/hashicorp/pandora/issues/4219

`tools/data-api-differ`: supporting for diffing Common Types

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_subscription_20254.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go

This PR adds a workaround for [this issue](https://github.com/Azure/azure-rest-api-specs/issues/20254) - which enables deleting a Subscription containing Nested Resources.
Whilst this is obviously a dangerous operation, and wants a feature-flag accordingly, it's still useful to have at any rate.
Related https://github.com/hashicorp/terraform-provider-azurerm/issues/12264

`tools/importer-rest-api-specs`: adding a workaround for https://github.com/Azure/azure-rest-api-specs/issues/20254

---

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_newrelic_29256.go
tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go

Ref:  https://github.com/Azure/azure-rest-api-specs/issues/29256

`tools/importer-rest-api-specs`: adding a workaround to cover NewRelic's identity type being misdefined

---

tools/importer-rest-api-specs/components/parser/models.go
tools/importer-rest-api-specs/components/parser/models_datafactorycustom_test.go
tools/importer-rest-api-specs/components/parser/testdata/model_using_datafactory_custom_types.json
tools/importer-rest-api-specs/internal/featureflags/constants.go

This PR parses the DataFactory custom types into regular Object Definitions, meaning that rather than outputting these as Objects we're correctly outputting these as whatever the type is.
I've currently enabled this for all of the Data Factory Custom Types **except** a List of a Reference - since these reference models outside the Swagger file we're loading and thus need to be loaded ahead of time. Once the remaining refactoring work is completed we can circle back and enable the remaining functionality - but this gets us the majority of the benefits for now, and we can rejig the loading order post-refactor.
Fixes https://github.com/hashicorp/pandora/issues/4026 - I'll open a replacement issue to track support for Data Factory references of a custom type
---
This causes a change in:
```
$ …
```

`tools/importer-rest-api-specs`: support for parsing the Data Factory custom types into regular Object Definitions

---

tools/generator-go-sdk/README.md
tools/generator-go-sdk/internal/cmd/generate.go
tools/generator-go-sdk/internal/generator/templater_id_parser_test.go
tools/generator-go-sdk/internal/generator/templater_methods.go

This PR fixes an issue spotted in the regeneration from https://github.com/hashicorp/pandora/pull/3958, where an extra new line is added to each Operation - leading to the big diff seen in https://github.com/hashicorp/go-azure-sdk/pull/1038
This PR also fixes the default port for the Data API used by the Go SDK Generator to be 8080 (to match V2) rather than 5000 (which was for V1).
Running a diff on the generated output from this branch, vs main shows:

`tools/generator-go-sdk`: sorting the `ClientOptions` alphabetically / removing blank lines

---

tools/importer-rest-api-specs/components/parser/normalization.go

This PR fixes OperationIDs such as `ManagementGroupSubscriptions_Example` being parsed as `Ubscriptions_Example` (and then normalised to `UbscriptionsExample`, as shown in https://github.com/hashicorp/go-azure-sdk/issues/1025)
Running `make import` on this shows the following diff:
```
❯ git status
On branch b/ubscriptions
Your branch is up to date with 'origin/b/ubscriptions'.
Changes to be committed:
(use "git restore --staged <file>..." to unstage)
renamed:    ../../api-definitions/resource-manager/ManagementGroups/2020-05-01/ManagementGroups/Operation-UbscriptionsCreate.json -> ../../api-definitions/resource-manager/ManagementGroups/2020-05-01/ManagementGroups/Operation-SubscriptionsCreate.json
renamed:    ../../api-definitions/resource-manager/ManagementGroups/2023-04-01/ManagementGro …
```

`tools/importer-rest-api-specs`: handling the case of `ManagementGroupSubscriptions` being truncated to `Ubscriptions`

---

tools/importer-rest-api-specs/components/parser/constants/interface.go

This occurred when importing `CDN` but is a legit bug/should be nil-check'd on our side too

`tools/importer-rest-api-specs`: fixing a nil crash

---

config/resource-manager.hcl

I am working on the new resource [System Center Virtual Machine Manager Virtual Machine Instance](https://github.com/Azure/azure-rest-api-specs/blob/ab064e0047ec560a700d6b501097d99471ad817b/specification/scvmm/resource-manager/Microsoft.ScVmm/stable/2023-10-07/scvmm.json#L157) but I found that it depends on the new resource [Hybrid Compute Machine resource](https://github.com/Azure/azure-rest-api-specs/blob/ab064e0047ec560a700d6b501097d99471ad817b/specification/hybridcompute/resource-manager/Microsoft.HybridCompute/preview/2024-05-20-preview/HybridCompute.json#L352). So I think we need to support Hybrid Compute Machine resource first. Given SCVMM RP team said that only latest preview API version of Hybrid Compute supports System Center Virtual Machine Manager Virtual Machine Instance and …

Config: add HybridCompute@2024-05-20-preview

---

config/resource-manager.hcl

This PR adds `DevOpsInfrastructure` `2024-04-04-preview` to support a new preview called `Managed DevOps Pool`
API Reference: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/devopsinfrastructure/resource-manager/Microsoft.DevOpsInfrastructure/preview/2024-04-04-preview

Added `DevOpsInfrastructure` `2024-04-04-preview`

---

config/resource-manager.hcl

The latest CDN API version 2024-02-01 can be successfully imported when the rest-api submodule is updated with PR #4335.

add `CDN@2024-02-01`

---

config/resource-manager.hcl

In order to support https://github.com/Azure/azure-rest-api-specs/blob/main/specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2024-05-01-preview/appplatform.json#L14130
The current implementation is using github.com/tombuildsstuff/kermit/sdk/appplatform/2023-05-01-preview/appplatform
and would like to start the work to migrate out of kermit and use hashicorp/go-azure-sdk instaed.

config - Adding support for AppPlatform 2024-05-01-preview to support Java_21

---

config/resource-manager.hcl

Reverts hashicorp/pandora#4415
the detect API changes action failed in the generated pr https://github.com/hashicorp/pandora/pull/4420 so reverting this to move long other PRs before investigation

Revert "config - Adding support for AppPlatform 2024-05-01-preview to support Java_21"

---

tools/importer-msgraph-metadata/components/normalize/duplicates.go
tools/importer-msgraph-metadata/components/normalize/duplicates_test.go
tools/importer-msgraph-metadata/components/normalize/verbs.go
tools/importer-msgraph-metadata/components/parser/resourceids.go
tools/importer-msgraph-metadata/components/parser/resources.go
tools/importer-msgraph-metadata/components/workarounds/workaround_blacklist.go
tools/importer-msgraph-metadata/components/workarounds/workaround_synchronizationsecrets.go
tools/importer-msgraph-metadata/components/workarounds/workarounds.go
tools/importer-msgraph-metadata/internal/pipeline/importer.go
tools/importer-msgraph-metadata/internal/pipeline/task_parse_resources.go
tools/importer-msgraph-metadata/internal/pipeline/task_translate_service.go

- Don't trim the final word when de-duplicating names
- When building resource names, only check for verbs and OData references in the final segment of the resource ID
- Blacklist some resources (`Calendar*` and `*TermStore*`) via a service workaround, since these are bothersome and we have no need to support them
- Perform post-parsing de-duplication of operations, which can happen due to very similar URIs that are sometimes functionally equivalent anyway
- When picking out duplicates, select the operation with the longest path and/or the longest resource ID name, as this is both deterministic and probably the most desirable outcome (longer paths tend to offer the most granular functionality)
- Internally, store any ad-hoc request models (i.e. service-specific request models) in the …

importer-msgraph-metadata: improvements to reduce duplicate resource/operation names and prevent clobbering

---

tools/generator-go-sdk/internal/generator/templater_models.go
tools/generator-go-sdk/internal/generator/templater_models_discriminators_test.go

When a model fields references an interface (i.e. a parent model), this currently fails to unmarshal. This PR fixes that by generating a temporary struct minus those such fields, unmarshalling into it, and then calling the explicit `Unmarshal{Foo}Implementation` function for that model.
Additionally, make the `Unmarshal{Foo}Implementation` functions more forgiving, so if the discriminated value field is missing, it continues to unmarshal into, and return, a `Raw{Foo}Impl` struct instead of just returning nil.

generator-go-sdk: fix unmarshalling fields that reference a model interface

---

tools/data-api-repository/repository/internal/models/operations.go
tools/data-api-repository/repository/internal/transforms/sdk_operation_option.go
tools/data-api-sdk/v1/models/sdk_operation_option.go
tools/generator-go-sdk/internal/generator/templater_methods.go
tools/generator-go-sdk/internal/generator/templater_methods_test.go
tools/importer-msgraph-metadata/internal/pipeline/task_parse_resources.go
tools/importer-msgraph-metadata/internal/pipeline/task_translate_service.go

* Add a `Type` to `SDKOperationOption` to accommodate additional options that are orthogonal to the existing marshallable options (which become headers, query string arguments, or odata settings).
* Support a caller-specified `Content-Type` header via `SDKOperationOptionTypeContentType`, useful for file uploads and other scenarios with a customizable request body.
* Support a caller-specified `RequestRetryFunc` via `SDKOperationOptionTypeRequestFunc`, more details below.
* For MS Graph API definitions, add a `RetryFunc` option to all operations.
* For MS Graph API definitions, add a `ContentType` option whenever the request body is a binary payload.
Currently we have some hardcoded RetryFuncs to handle specific error cases where we want to either safely retry the original request, to …

Support caller-specified RetryFuncs

---

tools/generator-go-sdk/internal/cmd/generate.go
tools/generator-go-sdk/internal/generator/data.go
tools/generator-go-sdk/internal/generator/settings.go
tools/generator-go-sdk/internal/generator/templater_models.go
tools/generator-go-sdk/internal/generator/templater_models_discriminators_test.go

Initial behavior to omit discriminated value when marshalling. Model behaviors are opt-in; enabled only for MS Graph at this time.
**Example SDK Output**
<br>
<br>

generator-go-sdk: support model behaviors

---

.github/workflows/automation-regenerate-terraform.yaml

Regenerate Terraform Provider GHA is failing with the current error message when running `make tools` in the provider codebase:
```
go: downloading go1.22 (linux/amd64)
go: download go1.22 for linux/amd64: toolchain not available
golangci/golangci-lint info checking GitHub for tag 'v1.55.1'
golangci/golangci-lint info found version: 1.55.1 for v1.55.1/linux/amd64
install: cannot create regular file '/bin/golangci-lint': Permission denied
```

GHA: bump go version for terraform generator

---

config/resource-manager.hcl

Enables device registry team to build the golang sdk for DeviceRegistry service (for the [go-azure-sdk ](https://github.com/hashicorp/go-azure-sdk/tree/main?tab=readme-ov-file) repo), then we can add DeviceRegistry to azurerm terraform: https://github.com/hashicorp/terraform-provider-azurerm
Specs to onboard: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/deviceregistry/resource-manager/Microsoft.DeviceRegistry/preview

config: adding DeviceRegistry 2023-11-01-preview / 2024-09-01-preview

---

config/resource-manager.hcl

I'm interested in adding support for issue https://github.com/hashicorp/terraform-provider-azurerm/issues/26575 and for that I think the first action is to add the preview api version `2024-06-01-preview` for the search service.

feat: add api 2024-06-01-preview of search service

---

config/resources/containerservice.hcl

The GHA to regenerate the Terraform provider fails with multiple errors that look similar to:
`cannot use id (variable of type "github.com/hashicorp/go-azure-sdk/resource-manager/containerservice/2024-04-01/fleets".FleetId) as "github.com/hashicorp/go-azure-sdk/resource-manager/containerservice/2023-10-15/fleets".FleetId value in argument to client.Get`
The client for the Kubernetes Fleet resources are shared by resources that are both manually written and generated by Pandora:
- `azurerm_kubernetes_fleet_manager` was previously generated by Pandora but was converted to a manually written resource due to limitations in generation
- `azurerm_kubernetes_fleet_member` is still generated by Pandora
The client was updated from `2023-10-15` to `2024-04-01` for Fleet Managers but the Pandora …

config - upgrade fleet members version to `2024-04-01`

---

tools/importer-rest-api-specs/internal/components/apidefinitions/parser/cleanup/to_sort.go

Source files and Service responses all use `Microsoft.Cdn` not `Microsoft.CDN`

`importer` - fixup casing for `Microsoft.Cdn` to avoid resource ID parsing errors

---

config/resource-manager.hcl

Given the following info, the desktopvirtualization API v2022-02-10-preview currently in use should be upgraded to 2024-04-08-preview.
```
On 11 March 2025, the following DesktopVirtualization APIs will no longer be supported, and you'll need to update to either API v. 2024-04-08-preview or API v. 2024-04-03: 
•	2021-08-04-preview 
•	2021-09-03-preview 
•	2022-01-12-privatepreview 
•	2022-02-10-preview 
•	2022-04-01-preview 
•	2022-08-09-privatepreview 
•	2023-01-28-privatepreview 
•	2023-01-30-preview 
•	2023-03-03-privatepreview 
•	2023-04-06-preview 
•	2023-11-01-preview 
•	2023-11-29-privatepreview 
•	2023-12-25-privatepreview 
If you update to API v. 2024-04-03, we recommend testing it first to see if it fits your needs, as API v. 2024-04-03 doesn't contain all the functionality as …
```

config: adding desktopvirtualization API v2024-04-08-preview

---

config/resource-manager.hcl

Since the currently used `desktopvirtualization` API v2022-02-10-preview would no longer be supported on 11 March 2025, we should upgrade the API version of the `desktopvirtualization` RP.
Previously, I added `desktopvirtualization` API v2024-04-08-preview in [PR](https://github.com/hashicorp/pandora/pull/4589). Although this is the version with full functions recommended in the email, I just received a feedback from the service team that it is not recommended to use the preview version and it is recommended to upgrade to stable v2024-04-03. In addition, after a rough comparison, the functions of 2022-02-10-preview, which is now used by Terraform, are included in stable v2024-04-03, so v2024-04-08-preview is deleted and replaced with the latest stable v2024-04-03.
Swagger: …

config: adding desktopvirtualization API v2024-04-03

---

tools/importer-msgraph-metadata/components/workarounds/workaround_oauth2permissiongrant.go
tools/importer-msgraph-metadata/components/workarounds/workarounds.go

According to docs, `clientId` is not updateable so it shouldn't be specified when patching.
- https://learn.microsoft.com/en-us/graph/api/oauth2permissiongrant-update?view=graph-rest-1.0
- https://learn.microsoft.com/en-us/graph/api/oauth2permissiongrant-update?view=graph-rest-beta
Related: https://github.com/hashicorp/terraform-provider-azuread/issues/1536

importer-msgraph-metadata: workaround for `clientId` field in `oAuth2PermissionGrant` model

---

docs/data-workarounds.md
tools/importer-rest-api-specs/internal/components/apidefinitions/parser/dataworkarounds/workaround_web_31682.go
tools/importer-rest-api-specs/internal/components/apidefinitions/parser/dataworkarounds/workarounds.go

This PR adds docs for how to create new overrides and adds a new override for Web

Add a new override and docs for how to add new overrides

---

tools/importer-rest-api-specs/internal/components/apidefinitions/parser/dataworkarounds/workaround_datafactory_27816.go
tools/importer-rest-api-specs/internal/components/apidefinitions/parser/dataworkarounds/workarounds.go

Related to:
https://github.com/tombuildsstuff/kermit/issues/381
https://github.com/hashicorp/terraform-provider-azurerm/issues/24998

dataworkaround: add workaround for datafactory 27816

---

config/resources/containerservice.hcl

to fix issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/28838
as suggested in https://github.com/hashicorp/pandora/pull/4467#issuecomment-2601830730, I'll disable the auto-gen here and change the resource to a manually written one.

Remove `kubernetes_cluster_trusted_access_role_binding` from the auto-generated resource

---

config/resource-manager.hcl

These resources were deprecated and removed in 4.0

config: remove `logz`

---

docs/data-workarounds.md
tools/importer-rest-api-specs/internal/components/apidefinitions/parser/dataworkarounds/workaround_sql_33215.go
tools/importer-rest-api-specs/internal/components/apidefinitions/parser/dataworkarounds/workarounds.go

Workaround for [azure-rest-api-specs#33215](https://github.com/Azure/azure-rest-api-specs/issues/33215)

dataworkaround: add workaround for Sql Job Agent Identity 33215

---

.github/dependabot.yml

Dependabot has stopped opening PRs to update the [Rest API specs submodule](https://github.com/Azure/azure-rest-api-specs/tree/78afda2a2c759dc0caa3a140a94021b322ca8f37) claiming the 2 open PR limit has been reached. There are no open dependabot PRs on the repo and after bumping this limit to 10 we still get the same error:

GHA: remove dependabot

---

tools/importer-rest-api-specs/internal/components/apidefinitions/parser/dataworkarounds/common_workaround_is_lro.go
tools/importer-rest-api-specs/internal/components/apidefinitions/parser/dataworkarounds/workarounds.go

Workaround needed to fully move `azurerm_backup_protected_vm` from `azure-sdk-for-go` to `go-azure-sdk`. Adding it as a common workaround since it looks like we'll need to use this for other resources in `recoveryservices` as well.
If this approach is acceptable, we could also remove `workaround_automation_25435.go` and replace it with `commonWorkaroundIsLRO`

add a common workaround for LROs not marked as LRO

---

tools/importer-rest-api-specs/internal/components/apidefinitions/parser/cleanup/normalize_api_definitions.go
tools/importer-rest-api-specs/internal/components/apidefinitions/parser/cleanup/pluralise_helper.go

This PR is an improvement for PR #4876 as filename or tags may already in special plural format, so `skus` should not be `skuses`

`importer`: do not repeat plural if input is already in plural

---

.github/workflows/unit-test-rest-api-specs-importer.yaml

removed fail fast as only relevant to matrix tests, and this workflow has no matrix.

`tooling` - Change runner to custom-linux-xl for unit tests
