config/resource-manager.hcl
Let's give it a try!
If it makes more sense to first migrate to the current API version, let me know
=> config: add `Microsoft.ContainerService` @ `2022-08-02-preview`

config/resource-manager.hcl
swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/hybridcompute/resource-manager/Microsoft.HybridCompute/stable/2022-03-10/HybridCompute.json
doc:
https://learn.microsoft.com/en-us/rest/api/hybridcompute/
=> config: add `hybridcompute` @ `2022-03-10`

config/resource-manager.hcl
Required to implement container-based immutability policies.
=> Add `storage@2022-05-01`

config/resource-manager.hcl
[Swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/connectedvmware/resource-manager/Microsoft.ConnectedVMwarevSphere/preview/2022-01-10-preview/connectedvmware.json)
=> Data: Add sdk for new service `connectedvmware`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 83dbe930ac67ec84dc204e1e68363c200cf18792
=> Config: regenerating based on 83dbe930ac67ec84dc204e1e68363c200cf18792

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit b63f1bedfc22509b7764c905bc82143df68bfa1b
=> Config: regenerating based on b63f1bedfc22509b7764c905bc82143df68bfa1b

config/resource-manager.hcl
[Swagger](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/networkfunction/resource-manager/Microsoft.NetworkFunction/stable/2022-11-01)
[Document](https://learn.microsoft.com/en-us/azure/expressroute/how-to-configure-traffic-collector)
=> config: Update api version for new resource `Network Function`

config/resource-manager.hcl
Fixes https://github.com/hashicorp/go-azure-sdk/issues/164
=> config: add `subscription` @ `2021-10-01`

config/resource-manager.hcl
Needed for https://github.com/hashicorp/terraform-provider-azurerm/issues/18062
=> config: add `CostManagement` @ `2022-06-01-preview`

config/resource-manager.hcl
Links:
swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2022-02-01/kusto.json doc: https://learn.microsoft.com/en-us/rest/api/azurerekusto/clusters/create-or-update?tabs=HTTP
Fixing https://github.com/hashicorp/pandora/issues/1727
=> add config `Micorsoft.Kusto@2022-02-01`

config/resource-manager.hcl
to add `immutabilitySettings` of recovery servcices vault
=> add `recoveryservices@2022-08-01`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 081cc35e583039ebe06a58fd46c3b59344418f17
=> Config: regenerating based on 081cc35e583039ebe06a58fd46c3b59344418f17

tools/generator-terraform/generator/mappings/assignment_direct.go, tools/generator-terraform/generator/mappings/assignment_direct_createorupdate_test.go, tools/generator-terraform/generator/mappings/assignment_direct_read_test.go, tools/generator-terraform/generator/resource/component_imports.go, tools/generator-terraform/generator/resource/component_imports_test.go, tools/importer-rest-api-specs/components/schema/processors/field_name_rename_boolean.go, tools/importer-rest-api-specs/components/schema/processors/models_test.go, tools/importer-rest-api-specs/components/testattributes/test_attributes.go, tools/importer-rest-api-specs/components/testattributes/test_attributes_commonschema_test.go
This PR fixes the Mappings for both Zones and Constants
=> tools/generator-terraform: fixing mappings for Zones/Constants

config/resource-manager.hcl
Adding ManagedServices 2022-10-01 to support new properties.
=> Add `ManagedServices` `2022-10-01`

config/resource-manager.hcl
Adding `LabServices` `2022-08-01` to support this RP.
=> Add `LabServices` `2022-08-01`

config/resource-manager.hcl
[Swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/deploymentScripts.json)
[Document](https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-script-template)
=> config: Update API version for new resource Deployment Scripts

config/resource-manager.hcl, config/resources/managedidentity.hcl
Prep for https://github.com/hashicorp/terraform-provider-azurerm/issues/18617
=> Add `msi@2022-01-31-preview`

config/resource-manager.hcl
Prep work to properly terraform https://learn.microsoft.com/en-us/azure/storage/common/azure-defender-storage-configure?toc=%2Fazure%2Fdefender-for-cloud%2Ftoc.json#terraform-template
=> Add `security@2022-03-01`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 7f89374a1ce45d7ad0f9181971ca620c132e2766
=> Config: regenerating based on 7f89374a1ce45d7ad0f9181971ca620c132e2766

config/resource-manager.hcl
[Swagger](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/resourceconnector/resource-manager/Microsoft.ResourceConnector/stable/2022-10-27)
[Azure Arc resource bridge](https://learn.microsoft.com/en-us/azure/azure-arc/resource-bridge/overview)
=> config: add resourceconnector@2022-10-27

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 0862a3aa045978c0c69953f17985d20e514b7331
=> Config: regenerating based on 0862a3aa045978c0c69953f17985d20e514b7331

config/resource-manager.hcl
[swagger](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2022-10-01)
[doc 
](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/overview)
=> config: upgrade cognitiveservices@2022-10-01

tools/importer-rest-api-specs/components/parser/models.go, tools/importer-rest-api-specs/components/parser/models_discriminators_test.go, tools/importer-rest-api-specs/components/parser/testdata/model_discriminators_inherited_from_discriminators.json
=> tools/importer-rest-api-specs: handling discriminators that inherit from other discriminators

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit f8d90e933308c03fcddf5fba74fac26fa552c003
=> Config: regenerating based on f8d90e933308c03fcddf5fba74fac26fa552c003

tools/importer-rest-api-specs/components/parser/cleanup/cleanup.go, tools/importer-rest-api-specs/components/parser/internal/helpers.go, tools/importer-rest-api-specs/components/parser/resourceids/parse_segments.go
Fixing issues discovered in #1840
=> tools/importer-rest-api-specs: fixing data issues from #1840

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 84201881567beb9dfc68aef4913dfbd1ec6c291b
=> Config: regenerating based on 84201881567beb9dfc68aef4913dfbd1ec6c291b

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 012ad342180d99399f66577951fdc18fca38b2c7
=> Config: regenerating based on 012ad342180d99399f66577951fdc18fca38b2c7

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 54a587f2aa10f4571280e63b434bcd28eab406a2
=> Config: regenerating based on 54a587f2aa10f4571280e63b434bcd28eab406a2

config/resource-manager.hcl
swagger:
- [media@2021-11-01](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/mediaservices/resource-manager/Microsoft.Media/Accounts/stable/2021-11-01)
- [media@2022-08-01](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/mediaservices/resource-manager/Microsoft.Media/Streaming/stable/2022-08-01)
=> config: add media `2021-11-01` and `2022-08-01`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit f360460da950ef2e56a18513b7cff467c92512cb
=> Config: regenerating based on f360460da950ef2e56a18513b7cff467c92512cb

config/resource-manager.hcl
add 2021-12-01 to swap sdk with https://github.com/hashicorp/terraform-provider-azurerm/pull/19551
=> add recoveryservices@2021-12-01

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 85cd039648081e83368537dc5a1344c3e79568d7
=> Config: regenerating based on 85cd039648081e83368537dc5a1344c3e79568d7

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 4dced5a3321b6ad2b7df28fb1c4070d126cec56c
=> Config: regenerating based on 4dced5a3321b6ad2b7df28fb1c4070d126cec56c

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 5183ec9407f7249a0a9f86830b0dac9e9a4bc58b
=> Config: regenerating based on 5183ec9407f7249a0a9f86830b0dac9e9a4bc58b

config/resource-manager.hcl
Add mysql API to enable implementation of CMK for https://github.com/hashicorp/terraform-provider-azurerm/issues/19842
=> config: add mysql 2021-05-01 & 2021-12-01-preview

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 608c1e923469f4972620d7b3e5fc8169cb5ba53c
=> Config: regenerating based on 608c1e923469f4972620d7b3e5fc8169cb5ba53c

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit fa805064716faea9ebf3b096b8b27398e16dfbc2
=> Config: regenerating based on fa805064716faea9ebf3b096b8b27398e16dfbc2

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 982a8860dca58a974ecd8620492b37fc15b401a7
=> Config: regenerating based on 982a8860dca58a974ecd8620492b37fc15b401a7

config/resource-manager.hcl
=> config: importing network @ 2022-07-01

config/resource-manager.hcl
Reverts hashicorp/pandora#2034
=> Revert "config: importing network @ 2022-07-01"

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 976d05236dabbcca7dff8564ad697e4e80d57a54
=> Config: regenerating based on 976d05236dabbcca7dff8564ad697e4e80d57a54

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 5eb1823b55688705ff9f9cabe6fa7b36e779df41
=> Config: regenerating based on 5eb1823b55688705ff9f9cabe6fa7b36e779df41

tools/importer-rest-api-specs/components/parser/resourceids/common_id_hyperv_site_job.go, tools/importer-rest-api-specs/components/parser/resourceids/common_id_hyperv_site_machine.go, tools/importer-rest-api-specs/components/parser/resourceids/common_id_hyperv_site_runasaccount.go, tools/importer-rest-api-specs/components/parser/resourceids/common_id_vmware_site_job.go, tools/importer-rest-api-specs/components/parser/resourceids/common_id_vmware_site_machine.go, tools/importer-rest-api-specs/components/parser/resourceids/common_id_vmware_site_runasaccount.go, tools/importer-rest-api-specs/components/parser/resourceids/common_ids.go
Dependent on https://github.com/hashicorp/go-azure-helpers/pull/143
=> tools/importer-rest-api-specs: adding Common IDs for Migrate

config/resource-manager.hcl
btw, the importer randomly lose "resourceid-xxx" files on my machine, I'm not sure if it works fine in CI
=> add migrate@2020-01-01

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 73fee8df189486f0e2b17a1a7e533f2ca1b3fb0b
=> Config: regenerating based on 73fee8df189486f0e2b17a1a7e533f2ca1b3fb0b

tools/generator-go-sdk/main.go
We'll add more services once the provider has the necessary plumbing to configure the new API client
See https://github.com/hashicorp/go-azure-sdk/pull/282#issuecomment-1418254609
=> Opt in ChaosStudio to new base layer

config/resource-manager.hcl
Swagger : https://github.com/Azure/azure-rest-api-specs/tree/main/specification/voiceservices/resource-manager/Microsoft.VoiceServices/stable/2023-01-31
=> config : add voiceservices@2023-01-31

config/resource-manager.hcl
Adding:
* `storagecache` @ `2021-09-01`
* `storagesync` @ `2020-03-01`
* `timeseriesinsights` @ `2020-05-15`
=> config: adding `storagecache` / `storagesync` and `timeseriesinsights`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 30029160275a8e7025aa157d8de8d0c75217b52f
=> Config: regenerating based on 30029160275a8e7025aa157d8de8d0c75217b52f

config/resource-manager.hcl
Update policy Assignment API version for new features.
=> Add `resources` version `2022-06-01`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit b4389b01b5e8d06164a39f76fe477aa909e66fb3
=> Config: regenerating based on b4389b01b5e8d06164a39f76fe477aa909e66fb3

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit b687b9003d7865b1d3347d62c97c8f8157c71b8e
=> Config: regenerating based on b687b9003d7865b1d3347d62c97c8f8157c71b8e

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 47e283772afa002ea303ac1589532e5aba9f281e
=> Config: regenerating based on 47e283772afa002ea303ac1589532e5aba9f281e

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit b28157a9f9da6bf82432a90e0051bbff2f6fc9b2
=> Config: regenerating based on b28157a9f9da6bf82432a90e0051bbff2f6fc9b2

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit dd8aaf85ecccdd3b9b9ae2591a5856c432dceea6
=> Config: regenerating based on dd8aaf85ecccdd3b9b9ae2591a5856c432dceea6

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 9059638d27fe2a8158549126af90e7e8f8301e9d
=> Config: regenerating based on 9059638d27fe2a8158549126af90e7e8f8301e9d

config/resource-manager.hcl
Swagger : https://github.com/Azure/azure-rest-api-specs/blob/main/specification/storagemover/resource-manager/Microsoft.StorageMover/stable/2023-03-01/storagemover.json#L916
=> config : add storagemover@2023-03-01

config/resource-manager.hcl
swagger: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/monitor/resource-manager/Microsoft.Insights/stable/2022-06-01
To onboard data collection new version.
=> Config: add monitor@2022-06-01

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 01620208759cd3da8715c431aed0ac384c7ee340
=> Config: regenerating based on 01620208759cd3da8715c431aed0ac384c7ee340

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit c10fb3489eb49a1f1efb2b3370fd3110cd093a66
=> Config: regenerating based on c10fb3489eb49a1f1efb2b3370fd3110cd093a66

tools/generator-terraform/generator/resource/docs/component_attributes.go, tools/generator-terraform/generator/resource/docs/component_attributes_test.go
Resolves https://github.com/hashicorp/terraform-provider-azurerm/pull/21177
=> tools/generator-terraform: updating the text used in the output

config/resource-manager.hcl
**NOTE:** This PR supersedes PR #2223
Fixes https://github.com/hashicorp/go-azure-sdk/issues/393
=> Search - Add support for 2022-09-01

config/resource-manager.hcl
Addresses https://github.com/hashicorp/terraform-provider-azurerm/pull/21304
=> Add support for dataprotection 2023-01-01

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 24f122adf077cf746362e0e95326eb5c8a202c73
=> Config: regenerating based on 24f122adf077cf746362e0e95326eb5c8a202c73

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit dac9c936d974cd546fa4b805bc9a916cf847e1f1
=> Config: regenerating based on dac9c936d974cd546fa4b805bc9a916cf847e1f1

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit c709fe6a9c4f26fd2ca2c03a7b74ddb7b50555b0
=> Config: regenerating based on c709fe6a9c4f26fd2ca2c03a7b74ddb7b50555b0

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit e08fced4bbec2d6b9991fb29a198476defbbe2f7
=> Config: regenerating based on e08fced4bbec2d6b9991fb29a198476defbbe2f7

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit fc5e5babef9debbf09c23a27990e6993900f05f0
=> Config: regenerating based on fc5e5babef9debbf09c23a27990e6993900f05f0

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 08d8de9ccffcb14f7596b82a2db4fd044f96cce4
=> Config: regenerating based on 08d8de9ccffcb14f7596b82a2db4fd044f96cce4

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 6e32447bd7d77cd6fd39f06f39c1f6206bfca38f
=> Config: regenerating based on 6e32447bd7d77cd6fd39f06f39c1f6206bfca38f

config/resource-manager.hcl
👋 This PR adds the 2022-09-01 Network API
https://learn.microsoft.com/en-us/rest/api/virtual-network/
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/network/resource-manager/Microsoft.Network/stable/2022-09-01
=> config: Add Network 2022-09-01

tools/importer-rest-api-specs/components/parser/cleanup/cleanup.go
=> importer-rest-api-specs: normalize segments in `Network` `2022-09-01`

config/resource-manager.hcl
Ignoring until a few SDK clients from network have been tested
=> config: ignore `network` `2022-11-01`

tools/importer-rest-api-specs/components/parser/models.go, tools/importer-rest-api-specs/components/parser/models_test.go, tools/importer-rest-api-specs/components/parser/testdata/model_containing_allof_within_properties_multiple.json
resolves #1377
I have tried to generate the SDK for CosmosDB and it looks fine.
=> Pull out nested model if it have multiple AllOf

tools/importer-rest-api-specs/components/parser/models.go, tools/importer-rest-api-specs/components/parser/models_discriminators_test.go, tools/importer-rest-api-specs/components/parser/testdata/model_discriminators_deep_inheritance.json
resolves https://github.com/hashicorp/pandora/issues/2233
Previous implementation did not scoping further than grandparent, so some models will get nil `ParentTypeName` and `TypeHintIn` value and be removed later as they aren't referenced. This PR will add below models:
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
data/Pandora.Definitions.ResourceManager/Media/v2021_11_01/Encodings/Model-JpgImage.cs
data/Pandora.Definitions.ResourceManager/Media/v2021_11_01/Encodings/Model-JpgLayer.cs
data/Pandora.Definitions.ResourceManager/Media/v2021_11_01/Encodings/Model-Layer.cs
data/Pandora.Definitions.ResourceManager/Media/v2021_11_01/Encodings/Model-PngImage.cs
data/Pandora.Definitions.ResourceManager/Media/v2022_07_01/Encodings/Model-JpgImage.cs …
```
=> tools/importer-rest-api-specs: find type from ancestor

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 5ed441f9fa1ae55b21bb00e5a3b76dec2c4c2f12
=> Config: regenerating based on 5ed441f9fa1ae55b21bb00e5a3b76dec2c4c2f12

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 73594141602ec2ddeb8adc5e65d4fc7816de79ec
=> Config: regenerating based on 73594141602ec2ddeb8adc5e65d4fc7816de79ec

config/resource-manager.hcl
=> config: remove `search` `2020-03-13` and `2020-08-01` as they're no longer used

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit bb1944d6fd13343ace2eb93b7eee168b5e0c6d0e
=> Config: regenerating based on bb1944d6fd13343ace2eb93b7eee168b5e0c6d0e

config/resource-manager.hcl
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/newrelic/resource-manager/NewRelic.Observability/stable/2022-07-01/NewRelic.json
https://learn.microsoft.com/en-us/azure/partner-solutions/new-relic/new-relic-overview
=> config: adding `newrelic`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit d4939a7aaf0865a9400d71d45fa6aaa3cd148e60
=> Config: regenerating based on d4939a7aaf0865a9400d71d45fa6aaa3cd148e60

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 71906db0f115f4ac1853a8d67892af242e155ff8
=> Config: regenerating based on 71906db0f115f4ac1853a8d67892af242e155ff8

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit c2e5dc687b5bdf32b483c42e42d3c511bf059980
=> Config: regenerating based on c2e5dc687b5bdf32b483c42e42d3c511bf059980

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 4de23652ee786a387d4ada54d4082087ef8b3c8c
=> Config: regenerating based on 4de23652ee786a387d4ada54d4082087ef8b3c8c

config/resource-manager.hcl
Fixes https://github.com/hashicorp/go-azure-sdk/issues/476
=> add containerservice@2023-04-02-preview

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_batch_21291.go
to unblock https://github.com/hashicorp/terraform-provider-azurerm/pull/21962
=> update `batch` storageAccountId workaround for `2022-10-01`

tools/importer-rest-api-specs/components/parser/commonschema/custom_field_identity_user_assigned_map.go, tools/importer-rest-api-specs/components/parser/models_identity_test.go, tools/importer-rest-api-specs/components/parser/testdata/model_user_assigned_map_with_additional_field.json, tools/importer-rest-api-specs/components/parser/testdata/model_user_assigned_map_with_tenant_id.json
=> importer-rest-api-specs: omit returning false if additional fields are defined for user assigned identity maps

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit b253f4fc0e1c2aa28c010ab73b9be3a09d3d8fcb
=> Config: regenerating based on b253f4fc0e1c2aa28c010ab73b9be3a09d3d8fcb

config/resource-manager.hcl
I intend to support PaloAltoNetworks RP. This is the API(https://github.com/Azure/azure-rest-api-specs/blob/main/specification/paloaltonetworks/resource-manager/PaloAltoNetworks.Cloudngfw/stable/2022-08-29/PaloAltoNetworks.Cloudngfw.json).
=> Config: add PaloAltoNetworks@2022-08-29

config/resource-manager.hcl
=> config: remove `PaloAltoNetworks` until resource ID segments are fixed

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 6692912a27f0eaff8845b8c2eb87239e8916c663
=> Config: regenerating based on 6692912a27f0eaff8845b8c2eb87239e8916c663

config/resource-manager.hcl
adding 2023-01-15 for OperationStatusesClient & OperationResultsClient
=> recoveryservicesbackup: add 2023-01-15

tools/importer-rest-api-specs/components/parser/cleanup/cleanup.go
=> [PaloAltoNetworks] Fix the segments and the resource provider to be with the right casing

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit d9ea4f946f65497295e2b5b1a2a252b34a9f604e
=> Config: regenerating based on d9ea4f946f65497295e2b5b1a2a252b34a9f604e

config/resource-manager.hcl
swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/graphservicesprod/resource-manager/Microsoft.GraphServices/stable/2023-04-13/graphservicesprod.json
=> config: add graph `2023-04-13`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit b321b260b25d84414dc3e29f27732c27f76f9c06
=> Config: regenerating based on b321b260b25d84414dc3e29f27732c27f76f9c06

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 109109ec8eb87030a44630ee2949c0762be7b14f
=> Config: regenerating based on 109109ec8eb87030a44630ee2949c0762be7b14f

tools/importer-rest-api-specs/components/parser/operations.go, tools/importer-rest-api-specs/components/parser/operations_test.go, tools/importer-rest-api-specs/components/parser/testdata/operations_single_with_header_options.json
=> Add support for decimals while importing

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit ef0b3efe13530820e6f46c7ca946804b310ddda7
=> Config: regenerating based on ef0b3efe13530820e6f46c7ca946804b310ddda7

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 4bdc8a9f6907c274f4c8b59e4d8bc0d703e0a5eb
=> Config: regenerating based on 4bdc8a9f6907c274f4c8b59e4d8bc0d703e0a5eb

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 825dc4a7774d6836a4e4768b9e03203c08f00fc7
=> Config: regenerating based on 825dc4a7774d6836a4e4768b9e03203c08f00fc7

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit ef6aa50a763016c1f92968bb55ced70c2ebb7d2e
=> Config: regenerating based on ef6aa50a763016c1f92968bb55ced70c2ebb7d2e

config/resource-manager.hcl
Supersedes #2735
Depends on:
* https://github.com/hashicorp/terraform-provider-azurerm/pull/22412
* https://github.com/hashicorp/terraform-provider-azurerm/pull/22470
* https://github.com/hashicorp/terraform-provider-azurerm/pull/22469
=> config: removing older versions of services

.github/workflows/automation-extract-tf-resource-ids.yaml, .github/workflows/automation-regenerate-go-sdk.yaml, .github/workflows/automation-regenerate-terraform.yaml, .github/workflows/automation-rest-api-specs-importer.yaml, .github/workflows/automation-version-bumper.yaml, .github/workflows/unit-test-end-to-end.yaml, .github/workflows/unit-test-generator-go-sdk.yaml, .github/workflows/unit-test-generator-terraform.yaml, .github/workflows/unit-test-rest-api-specs-importer.yaml, README.md, tools/extract-tf-resource-ids/go.mod, tools/generator-go-sdk/go.mod, tools/generator-terraform/go.mod, tools/importer-rest-api-specs/go.mod, tools/sdk/go.mod, tools/version-bumper/go.mod, tools/wrapper-automation/go.mod
=> tooling: updating to Go 1.20.5

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit f8684020c0b4d0f8095fbf3e1d4d9a89212a6c64
=> Config: regenerating based on f8684020c0b4d0f8095fbf3e1d4d9a89212a6c64

config/resource-manager.hcl
To onboard Azure Native Qumulo Scalable File Service
swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/liftrqumulo/resource-manager/Qumulo.Storage/stable/2022-10-12/Qumulo.Storage.json
doc: https://learn.microsoft.com/en-us/azure/partner-solutions/qumulo/qumulo-create
=> add QumuloStorage 2022-10-12

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 594fe866230d210b63a4aeaf1a811f6c411eeae0
=> Config: regenerating based on 594fe866230d210b63a4aeaf1a811f6c411eeae0

config/resource-manager.hcl
Re-opening https://github.com/hashicorp/pandora/pull/2660
=> Add support for compute 2023-03-01

config/resource-manager.hcl
Reverts hashicorp/pandora#2807
=> Revert "Add support for compute 2023-03-01"

config/resource-manager.hcl
There's nothing blocking this, so this should be fine to merge
=> data: importing `DataDog` @ `2022-06-01`

config/resource-manager.hcl
https://github.com/hashicorp/pandora/issues/2236 is now fixed, so we can import this
=> data: importing `APIManagement` @ `2022-08-01`

config/resource-manager.hcl
Fixes https://github.com/hashicorp/go-azure-sdk/issues/469 Fixes https://github.com/hashicorp/go-azure-sdk/issues/470
=> data: supporting `ContainerApps` @ `2022-11-01-preview`

tools/importer-rest-api-specs/components/parser/cleanup/cleanup.go
Fixes an issue spotted in #2850
=> tools/importer-rest-api-specs: fixing the segments for machine learning workspace

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit c77815928eacc4398c7fad536cc98e038bcf8e9b
=> Config: regenerating based on c77815928eacc4398c7fad536cc98e038bcf8e9b

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit ca1e26ff5c8460cba7a1da2b3e1ca503fbf59737
=> Config: regenerating based on ca1e26ff5c8460cba7a1da2b3e1ca503fbf59737

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit fdff57cb80a0da4e5f1cd1ea52d263828ea1864d
=> Config: regenerating based on fdff57cb80a0da4e5f1cd1ea52d263828ea1864d

config/resource-manager.hcl
There's nothing blocking this one, so should be fine to merge
=> data: adding `DataProtection` @ `2023-05-01`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit a82e6dedbbcca3b969e5eb3bcb25a31422b9efa8
=> Config: regenerating based on a82e6dedbbcca3b969e5eb3bcb25a31422b9efa8

config/resource-manager.hcl
This updates configuration to generate SDK for new NetworkCloud service
=> New NetworkCloud into SDK generation

config/resource-manager.hcl
prepare for https://github.com/hashicorp/terraform-provider-azurerm/issues/21388
swagger: https://github.com/Azure/azure-rest-api-specs/blob/624dbc769880e5676ae8bb20d3c82ebd1783c64a/specification/compute/resource-manager/Microsoft.Compute/DiskRP/stable/2023-04-02/diskRPCommon.json#L369
=> config: add `compute` `2023-04-02`

config/resource-manager.hcl
Adding container registry version 2023-06-01-preview. This is to update the ACR API from 2021-08-01-preview, that is used by the provider.
=> config: Add container registry version 2023-06-01-preview

config/resource-manager.hcl
PR in azurerm provider: https://github.com/hashicorp/terraform-provider-azurerm/pull/22308
Swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/automanage/resource-manager/Microsoft.Automanage/stable/2022-05-04/automanage.json
=> `Automanage` @ `2022-05-04` - add new resource provider into go-azure-sdk

tools/importer-rest-api-specs/components/parser/models.go, tools/importer-rest-api-specs/components/parser/models_discriminators_test.go, tools/importer-rest-api-specs/components/parser/swagger_resources.go, tools/importer-rest-api-specs/components/parser/testdata/model_discriminators_multiple_parents.json, tools/importer-rest-api-specs/components/parser/testdata/model_discriminators_multiple_parents_within_array.json
Some Swagger definitions define a Model which inherits from a Model which inherits from a Discriminated Parent Type, for example the Model `Human` (with a Discriminated Value) inherits from `NamedEntity` (containing only properties) which inherits from the type `BiologicalEntity` (which is a Discriminated Parent Type)
Fixes https://github.com/hashicorp/go-azure-sdk/issues/200
Diff from this change:
```diff
$ git diff HEAD
diff --git a/data/Pandora.Definitions.ResourceManager/AppPlatform/v2022_09_01_preview/AppPlatform/Definition.cs b/data/Pandora.Definitions.ResourceManager/AppPlatform/v2022_09_01_preview/AppPlatform/Definition.cs
index e19c0433ef..a85c777cbb 100644
--- a/data/Pandora.Definitions.ResourceManager/AppPlatform/v2022_09_01_preview/AppPlatform/Definition.cs
+++ …
```
=> `tools/importer-rest-api-specs`: pulling out models which inherit from models which inherit from discriminated parent types

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 782c618dd19a456108f868a3755b39e92dbfacd2
=> Config: regenerating based on 782c618dd19a456108f868a3755b39e92dbfacd2

config/resource-manager.hcl
See #3050 and https://github.com/hashicorp/pandora/pull/3047
=> config: ignoring `migrate` @ `2023-06-06`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit b63f62e2475293f9a3b7577289ec010110987d51
=> Config: regenerating based on b63f62e2475293f9a3b7577289ec010110987d51

config/resource-manager.hcl
this version is required to add new properties for `azurerm_log_analytics_cluster`
=> add `OperationalInsights@2021-06-01`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 76c8468e25c130d03200de24f9b13d3e5df7a094
=> Config: regenerating based on 76c8468e25c130d03200de24f9b13d3e5df7a094

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit b1412a6355332e4857d55e56074846ab1f04fe8d
=> Config: regenerating based on b1412a6355332e4857d55e56074846ab1f04fe8d

config/resource-manager.hcl
These two versions are currently used in the provider
=> config: adding API Versions for Application Insights

.github/workflows/automation-msgraph-metadata-importer.yaml, .github/workflows/automation-regenerate-go-sdk.yaml
=> actions: updating to use Go 1.21.3 consistently

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 5f967add0479e4cf37bc9805abe163c00f0f2a99
=> Config: regenerating based on 5f967add0479e4cf37bc9805abe163c00f0f2a99

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit f6e092c721872aa6137351945b31e065f1cb2c73
=> Config: regenerating based on f6e092c721872aa6137351945b31e065f1cb2c73

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit ee4b0681ac1b6bdfbf4b7069d11a5d7b976727d8
=> Config: regenerating based on ee4b0681ac1b6bdfbf4b7069d11a5d7b976727d8

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 79e6a85db4545f8b7f7e9a4ea409d4c3e62114d7
=> Config: regenerating based on 79e6a85db4545f8b7f7e9a4ea409d4c3e62114d7

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit fa4a5feca39c00f38f86661e854687758566d7c9
=> Config: regenerating based on fa4a5feca39c00f38f86661e854687758566d7c9

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit bcd0d3b5979202e23724343e3b84efb6c7802cff
=> Config: regenerating based on bcd0d3b5979202e23724343e3b84efb6c7802cff

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 22e7348a9630173ced296e0fdc4cfcd05cc8b3ff
=> Config: regenerating based on 22e7348a9630173ced296e0fdc4cfcd05cc8b3ff

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 908a30be00c3ac29ed52d12f68e97e2f76497d95
=> Config: regenerating based on 908a30be00c3ac29ed52d12f68e97e2f76497d95

tools/data-api/internal/repositories/helpers.go, tools/data-api/internal/repositories/models.go, tools/data-api/internal/repositories/services.go
Data API V2 is currently failing on main. 
I've added additional error messaging to see where we were going wrong and added additional ObjectDefinitionTypes to fix what was broken
=> DataAPIV2: Add additional error messaging when loading files and add additional ObjectDefinitionTypes 

tools/importer-rest-api-specs/components/parser/resourceids/common_id_shared_image_gallery.go, tools/importer-rest-api-specs/components/parser/resourceids/common_ids.go
Depends on https://github.com/hashicorp/go-azure-helpers/pull/191
=> tools/importer-rest-api-specs: adding common ids for shared image gallery

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit aafb8f550696bbcf5e45408f2199fe379dca1842
=> Config: regenerating based on aafb8f550696bbcf5e45408f2199fe379dca1842

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 18d489501c13b822dbbc365e82f79b3f625cad86
=> Config: regenerating based on 18d489501c13b822dbbc365e82f79b3f625cad86

tools/data-api/internal/repositories/services.go
=> dataapiv2 - fix issue where partial data is loaded

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 2efb7f2c16262ed94f67dcb5cd82f995155a20ee
=> Config: regenerating based on 2efb7f2c16262ed94f67dcb5cd82f995155a20ee

tools/importer-rest-api-specs/components/dataapigeneratorjson/templater_terraform_mappings.go
Fixes #3267
Also fixes a bug where we weren't removing the duplicated ModelToModelMappings
=> dataapigeneratorjson/templater_terraform_mappings - Add additional ModelToModelMappings

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 2c37d9b9f39e7bab600abda48ea3ef8ae18aeec3
=> Config: regenerating based on 2c37d9b9f39e7bab600abda48ea3ef8ae18aeec3

tools/data-api/internal/commands/serve.go, tools/data-api/main.go
=> dataapiv2: Add support for specifying `port` and `data-directory`

config/resource-manager.hcl
Needed for postgres 16: https://github.com/Azure/azure-rest-api-specs/blob/a4b7802e963b3a77b885d8c7c1616cd1870877fb/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/preview/y/FlexibleServers.json#L394
=> Add postgresql 2023-06-01-preview API

tools/importer-rest-api-specs/components/parser/cleanup/cleanup.go
Fixing a data issue identified in #3360
=> `tools/importer-rest-api-specs`: updating the segment `virtualendpoints` to be `virtualEndpoints`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit be4dfdb2b1c65231c9d299d35f52b826b501da2c
=> Config: regenerating based on be4dfdb2b1c65231c9d299d35f52b826b501da2c

tools/generator-go-sdk/generator/templater_id_parser.go, tools/generator-go-sdk/generator/templater_id_parser_test.go
partially addresses https://github.com/hashicorp/go-azure-helpers/issues/190
=> `tools/generator-go-sdk` - add FromParseResult on id generator

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 3f5d0ada2c5a8003eae90258e0f9cf65b49e4483
=> Config: regenerating based on 3f5d0ada2c5a8003eae90258e0f9cf65b49e4483

scripts/automation-generate-and-commit-go-sdk.sh, scripts/automation-generate-and-commit-terraform.sh, scripts/automation-generate-go-sdk.sh, scripts/automation-generate-terraform.sh, tools/data-api/internal/endpoints/routing.go, tools/wrapper-automation/go_sdk_generator.go, tools/wrapper-automation/models.go, tools/wrapper-automation/run.go, tools/wrapper-automation/terraform_generator.go
This PR adds a flag to `wrapper-automation` and the scripts that call `wrapper-automation` that will flips between the old and new data api
=> wrapper-automation - Add args.UseV2Generator

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit aed86d7619b2fa94b94736be48e449982ef8c301
=> Config: regenerating based on aed86d7619b2fa94b94736be48e449982ef8c301

config/resource-manager.hcl
Dependent on https://github.com/hashicorp/terraform-provider-azurerm/pull/23576
=> config: removing older versions of NetApp

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 0e8e17b32457b953b298ce511b461924fc110e0b
=> Config: regenerating based on 0e8e17b32457b953b298ce511b461924fc110e0b

config/resource-manager.hcl
adding this old version to do sdk-swap at same API version first for `azurerm_role_definition`,  will do sdk upgrade for it after the sdk-swap.
=> add Authrozition@2020-04-01-preview

scripts/automation-determine-changes-to-api-definitions.sh
Fixes https://github.com/hashicorp/pandora/pull/3500#issuecomment-1857674623
=> automation: flipping the diff ordering

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 9384ad82ff8597e0e31060fd8e01943ad4dbf356
=> Config: regenerating based on 9384ad82ff8597e0e31060fd8e01943ad4dbf356

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit c29bfa6002ad11710057c9c1d98e3fa980b7d494
=> Config: regenerating based on c29bfa6002ad11710057c9c1d98e3fa980b7d494

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 137002d03d5992ee8ebe44aa0367c19d7ef72274
=> Config: regenerating based on 137002d03d5992ee8ebe44aa0367c19d7ef72274

config/resource-manager.hcl
Reverts hashicorp/pandora#3550 because network is scary
=> Revert "Config: regenerating based on 137002d03d5992ee8ebe44aa0367c19d7ef72274"

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 39ddaa10da4a493ca01849298fb26f3b1e2dc839
=> Config: regenerating based on 39ddaa10da4a493ca01849298fb26f3b1e2dc839

tools/generator-terraform/generator/mappings/assignments.go
Fixes https://github.com/hashicorp/pandora/actions/runs/7538602136/job/20519702891
=> generator-terraform: nil check ModelToModel mappings

tools/importer-rest-api-specs/components/testing/complete.go
Fixes https://github.com/hashicorp/pandora/actions/runs/7571557477/job/20619333989
=> importer-rest-api-specs - nil check reference name when determining nested optional fields

tools/generator-terraform/generator/definitions/template_service_client.go, tools/generator-terraform/generator/definitions/template_service_client_test.go
fixes https://github.com/hashicorp/pandora/issues/3638
=> use common client options to configure clients

config/resource-manager.hcl
Adding support for the [billing service APIs](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/billing/resource-manager/readme.md) as I'd like to help develop and use these in the AzureRM terraform provider.
Included the two stable versions "2020-05-01" and "2021-10-01". Also included "2019-10-01-preview" as there are quite a few things in here which haven't yet made it to stable which would be useful.
=> Add support for billing service

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 77fb7532fa789c5e6a7b182245d7717668cf1c4e
=> Config: regenerating based on 77fb7532fa789c5e6a7b182245d7717668cf1c4e

tools/wrapper-automation/go_sdk_generator.go, tools/wrapper-automation/models.go, tools/wrapper-automation/rest_api_specs_importer.go, tools/wrapper-automation/run.go, tools/wrapper-automation/terraform_generator.go
=> `tools/wrapper-automation`: removing the conditional support for Data API V1

config/resource-manager.hcl
In purpose of supporting the latest released property `premiumMessagingPartitions`
=> `servicebus` - add api `2022-10-01-preview` 

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit d9fde06ca723ecb372ae860e0704b99e5cab0099
=> Config: regenerating based on d9fde06ca723ecb372ae860e0704b99e5cab0099

config/resource-manager.hcl
Dependent on https://github.com/hashicorp/pandora/pull/3720
=> config: importing `APIManagement` @ `2023-05-01-preview`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 407f72596ac5eb71f18a5b057559629e877b95d0
=> Config: regenerating based on 407f72596ac5eb71f18a5b057559629e877b95d0

config/resource-manager.hcl
As @wuxu92 has mentioned, this now appears to be resolved: https://github.com/hashicorp/pandora/issues/1508#issuecomment-1920933453
Fixes https://github.com/hashicorp/pandora/issues/1508
=> config: importing `Synapse` @ `2021-06-01`

tools/importer-rest-api-specs/components/schema/fields_resource_id.go, tools/importer-rest-api-specs/components/schema/fields_resource_id_test.go
=> `importer-rest-api-specs` - apply schema overrides to parent resource ID

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 82aef7d565064c5e9938d35abe84f7deb6189b17
=> Config: regenerating based on 82aef7d565064c5e9938d35abe84f7deb6189b17

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 242f37b0b49902b3aa59ad455cf734fd388463fc
=> Config: regenerating based on 242f37b0b49902b3aa59ad455cf734fd388463fc

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit b653e4b172a0bec47d94e8bd8602100097a95c9f
=> Config: regenerating based on b653e4b172a0bec47d94e8bd8602100097a95c9f

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit cdcd6dc53094e79a310f2f29e4f3538dbe48381a
=> Config: regenerating based on cdcd6dc53094e79a310f2f29e4f3538dbe48381a

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit dc105a5080b1a8ef0024c60c4b560912cd06cc08
=> Config: regenerating based on dc105a5080b1a8ef0024c60c4b560912cd06cc08

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 1242364608dcb92e8b857cf0fd06f135542d8786
=> Config: regenerating based on 1242364608dcb92e8b857cf0fd06f135542d8786

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit b285681c2967b032b464f45e0e0bce2bc38c9dce
=> Config: regenerating based on b285681c2967b032b464f45e0e0bce2bc38c9dce

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit c997af73b2d75c8ca25297146a20cde6eb63d1ed
=> Config: regenerating based on c997af73b2d75c8ca25297146a20cde6eb63d1ed

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 808b0b9232262e7243cac666b89c3bdcf208a957
=> Config: regenerating based on 808b0b9232262e7243cac666b89c3bdcf208a957

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit c278e6999c04c89f54f51ca9afa94dd09e6356dd
=> Config: regenerating based on c278e6999c04c89f54f51ca9afa94dd09e6356dd

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 2035aee7185e60fc5460a87e09063ad70261c3e8
=> Config: regenerating based on 2035aee7185e60fc5460a87e09063ad70261c3e8

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit b8c0d38be00f0848250323a1b524d2e09d9546a4
=> Config: regenerating based on b8c0d38be00f0848250323a1b524d2e09d9546a4

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit f1c375ecf0a9b044a54590823ce143234c89812f
=> Config: regenerating based on f1c375ecf0a9b044a54590823ce143234c89812f

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit cf0cd924d855ab4d2c5dc55f1d221f96a37cca56
=> Config: regenerating based on cf0cd924d855ab4d2c5dc55f1d221f96a37cca56

tools/importer-rest-api-specs/components/parser/cleanup/cleanup.go
Found in `SecurityInsights` `2024-03-01`
https://github.com/hashicorp/pandora/pull/3976
=> `importer-rest-api-specs` - camelcase resource ID segment `contentproductiontemplates` 

tools/importer-rest-api-specs/components/parser/models.go
There are several cases in Data Factory where the orphaned discriminated models are being parsed as non-discriminated models because the discriminator information lives in the parent.
Example:
Orphaned discriminated model: 
https://github.com/Azure/azure-rest-api-specs/blob/44a81f85be1e4797fbf5e290fc6b41d48788a6ba/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Credential.json#L98-L116
Parent model: 
https://github.com/Azure/azure-rest-api-specs/blob/44a81f85be1e4797fbf5e290fc6b41d48788a6ba/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Credential.json#L78-L87
This change will parse orphaned models that inherit from a parent and determine the discriminator information from the parent as well as …
=> `importer-rest-api-specs` - correctly update orphaned discriminated models with information from the parent

tools/importer-rest-api-specs/components/parser/dataworkarounds/workaround_datafactory_28122.go, tools/importer-rest-api-specs/components/parser/dataworkarounds/workarounds.go
Added a data workaround for DataFactory
=> dataworkaround - `DataFactory` `2018-06-01` add data workaround for datafactory 21822

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 14bdd8b750d0f35c7af579ec26bc26304a56c96b
=> Config: regenerating based on 14bdd8b750d0f35c7af579ec26bc26304a56c96b

config/resource-manager.hcl
This version adds many options.
Should be useful for https://github.com/hashicorp/terraform-provider-azurerm/issues/23988
=> config: add cognitiveservices 2023-10-01-preview

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 7e3033ac64aa5d8384a70638c8d46d7a2fe79efc
=> Config: regenerating based on 7e3033ac64aa5d8384a70638c8d46d7a2fe79efc

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit c19e782f2cf80415fe53fa453ce5178e2010220d
=> Config: regenerating based on c19e782f2cf80415fe53fa453ce5178e2010220d

config/resource-manager.hcl
Hi,
PR adds Azure Quota Service
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/quota/resource-manager/Microsoft.Quota/stable/2023-02-01
=> chore: add azure quota service

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 057b29ea1ce9ff43d4164a8d47e67da636252841
=> Config: regenerating based on 057b29ea1ce9ff43d4164a8d47e67da636252841

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit e1cdd4b3d009552758110f89e88a14a91f187879
=> Config: regenerating based on e1cdd4b3d009552758110f89e88a14a91f187879

config/resource-manager.hcl
* Add new API version for HDInsight.
=> Add HDInsight 2024-05-01

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 7e64ec3b0b10b7afc28d0b671a650da2f376108c
=> Config: regenerating based on 7e64ec3b0b10b7afc28d0b671a650da2f376108c

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit a881ae65d1fcb581d585586ffc625e9b34781489
=> Config: regenerating based on a881ae65d1fcb581d585586ffc625e9b34781489

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit f52459c781e46b88ef458793c70ff8e9c2497bbe
=> Config: regenerating based on f52459c781e46b88ef458793c70ff8e9c2497bbe

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 502c0758b9d5abb47eddbde90dfd89d8260ab3ae
=> Config: regenerating based on 502c0758b9d5abb47eddbde90dfd89d8260ab3ae

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 0c438b67bccbceb90eaf67072037528dcdde0251
=> Config: regenerating based on 0c438b67bccbceb90eaf67072037528dcdde0251

config/resource-manager.hcl
swagger: https://github.com/Azure/azure-rest-api-specs/tree/f2b603440c0c890cbaf6ddb1e6976bfcf14aa495/specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15
=> config - add network analytics @2023-11-15

config/resource-manager.hcl
Fixes https://github.com/hashicorp/pandora/issues/4160
=> config: adding `mysql` @ `2023-12-30`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit b8b7a89d7c58b71165e21aa83e3d7edebafcd5d8
=> Config: regenerating based on b8b7a89d7c58b71165e21aa83e3d7edebafcd5d8

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 1158c09c9cd037ccbce1fbc4d5f0680c21168c99
=> Config: regenerating based on 1158c09c9cd037ccbce1fbc4d5f0680c21168c99

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit e0744d41918374717d5d0069c0496ba56e17ac7f
=> Config: regenerating based on e0744d41918374717d5d0069c0496ba56e17ac7f

config/resource-manager.hcl
swagger: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/informatica
SDK generated successful in local env: 
```
➜  generator-go-sdk git:(main) ✗ ./generator-go-sdk resource-manager generate -output-dir $HOME/azure/go-azure-sdk -services=Informatica
2024/07/03 21:33:26 [DEBUG] GET http://localhost:8080/v1/resource-manager/services
2024/07/03 21:33:37 [DEBUG] GET http://localhost:8080/v1/resource-manager/common-types
2024/07/03 21:33:37 [DEBUG] GET http://localhost:8080/v1/resource-manager/services/Informatica
2024/07/03 21:33:37 [DEBUG] GET http://localhost:8080/v1/resource-manager/services/Informatica/2024-05-08
2024/07/03 21:33:37 [DEBUG] GET http://localhost:8080/v1/resource-manager/services/Informatica/2024-05-08/Organizations/operations
2024/07/03 21:33:37 …
```
=> `config`: add a new service `Informatica`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit f171497834b5196bc778a304ebec783be593e095
=> Config: regenerating based on f171497834b5196bc778a304ebec783be593e095

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 00539fe439e262b7966a83c9591d9d0cc6d8e2ca
=> Config: regenerating based on 00539fe439e262b7966a83c9591d9d0cc6d8e2ca

config/resource-manager.hcl
This PR is to add new service `sql` `2023-08-01-preview` for new GA feature request
API Reference: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/sql/resource-manager/Microsoft.Sql/preview/2023-08-01-preview
=> Add `sql` `2023-08-01-preview`

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 2e2ab089c0f906ba389dfd4300385b4347e580bf
=> Config: regenerating based on 2e2ab089c0f906ba389dfd4300385b4347e580bf

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit b0f7a486b1e6540f7933ab9e82cf29f746b8ff3e
=> Config: regenerating based on b0f7a486b1e6540f7933ab9e82cf29f746b8ff3e

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 9a3e31ee2dcd4f2d6abd09c7969e3616d87d9a97
=> Config: regenerating based on 9a3e31ee2dcd4f2d6abd09c7969e3616d87d9a97

config/resource-manager.hcl
* Added new service OracleDatabase 2024-06-01
Tested locally:
=> Added new service OracleDatabase 2024-06-01

config/resource-manager.hcl
Swagger:
https://github.com/Azure/azure-rest-api-specs/tree/release-azurefleet-Microsoft.AzureFleet-preview/2024-05-01-preview/specification/azurefleet/resource-manager/Microsoft.AzureFleet/preview/2024-05-01-preview
=> add azurefleet@2024-05-01-preview

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 5e36a8c53eb91a8ac8ed4d58df2ebc8582716c59
=> Config: regenerating based on 5e36a8c53eb91a8ac8ed4d58df2ebc8582716c59

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 07e283a2a699f67d05b5bd8422669a3df21859eb
=> Config: regenerating based on 07e283a2a699f67d05b5bd8422669a3df21859eb

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 71cccf637325e9f2fd7072a3663525138a07bcd7
=> Config: regenerating based on 71cccf637325e9f2fd7072a3663525138a07bcd7

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 08f4e0bee99b7e71ec5e8317d75e07d3d2475ec3
=> Config: regenerating based on 08f4e0bee99b7e71ec5e8317d75e07d3d2475ec3

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 2931cc745b4718eab72556bc00fb0ae63a26d190
=> Config: regenerating based on 2931cc745b4718eab72556bc00fb0ae63a26d190

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 65f3c0f75c5b24bccadc3777313b06f8cdab9247
=> Config: regenerating based on 65f3c0f75c5b24bccadc3777313b06f8cdab9247

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 77774af2f6011e7a18e70ad919ebec75f04c154e
=> Config: regenerating based on 77774af2f6011e7a18e70ad919ebec75f04c154e

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit e6125a825ade3fad7774b10166fad1123ad6b3fe
=> Config: regenerating based on e6125a825ade3fad7774b10166fad1123ad6b3fe

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit f521a08772b46550d4be9b86f26f9ec4d3c41df6
=> Config: regenerating based on f521a08772b46550d4be9b86f26f9ec4d3c41df6

config/resource-manager.hcl
Swagger: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/standbypool/resource-manager/Microsoft.StandbyPool/stable/2024-03-01
=> add standbypool@2024-03-01

config/resource-manager.hcl
Adding containerregistry 2023-11-01-preview (the azurerm provider is using 2023-06-01-preview at the moment).
=> config - Add containerregistry 2023-11-01-preview

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 76f9e273638d5e01011767c1f953ae8da2d5e3bd
=> Config: regenerating based on 76f9e273638d5e01011767c1f953ae8da2d5e3bd

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 65aed019d5c5b3209f62ecb509d6c1c363ac28ae
=> Config: regenerating based on 65aed019d5c5b3209f62ecb509d6c1c363ac28ae

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit e9b9b1cddc30f73afdd5ce632d0c6cea5398169e
=> Config: regenerating based on e9b9b1cddc30f73afdd5ce632d0c6cea5398169e

config/resource-manager.hcl
Add machinelearningservices `v2024-10-01-preview`
Swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/workspaceRP.json#L7100
=> Add Machine Learning workspace `v2024-10-01-preview`

config/resource-manager.hcl
2023-12-01-preview is the API version portal using, add it and update the resource to keep consistent.
=> add securityInsight@2023-12-01-preview

config/resource-manager.hcl
Add containerservice API v2024-09-01 to implement new properties such as advancedNetwork under networkProfile,
=> config: adding containerservice API v2024-09-01

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 6e06f0a3b8734c0d5636a21b32eaf62848c4ea2c
=> Config: regenerating based on 6e06f0a3b8734c0d5636a21b32eaf62848c4ea2c

tools/importer-rest-api-specs/internal/components/apidefinitions/parser/dataworkarounds/workaround_containerregistry_32154.go, tools/importer-rest-api-specs/internal/components/apidefinitions/parser/dataworkarounds/workarounds.go
For https://github.com/hashicorp/terraform-provider-azurerm/pull/27528
=> dataworkaround: add workaround for containerregistry 32154

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit ff5d0a36dab8d7b1acf3d1886d4d46278dd02345
=> Config: regenerating based on ff5d0a36dab8d7b1acf3d1886d4d46278dd02345

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 459f33a2fcff1ac914ffaa1d9d8cc229344d5b7e
=> Config: regenerating based on 459f33a2fcff1ac914ffaa1d9d8cc229344d5b7e

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 0a2f4794eb388c8a0855ab6aa648bb3384b55a2b
=> Config: regenerating based on 0a2f4794eb388c8a0855ab6aa648bb3384b55a2b

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit ace7c0953164fd159f94698f63b46135d14badf8
=> Config: regenerating based on ace7c0953164fd159f94698f63b46135d14badf8

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 4866523a5d37fe1c9f60b49d754aa0b5b7130272
=> Config: regenerating based on 4866523a5d37fe1c9f60b49d754aa0b5b7130272

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 22983fc467e8454fa2565d46ad19bfb9c3ec1d72
=> Config: regenerating based on 22983fc467e8454fa2565d46ad19bfb9c3ec1d72

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 4e12009d6f8b01337f123f1eb6a6be8d148987aa
=> Config: regenerating based on 4e12009d6f8b01337f123f1eb6a6be8d148987aa

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 43f0274aed95b316e3a77b5641cfd305437a9e89
=> Config: regenerating based on 43f0274aed95b316e3a77b5641cfd305437a9e89

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit dcf1fa4b03484a10538c32959d82b8d58724a330
=> Config: regenerating based on dcf1fa4b03484a10538c32959d82b8d58724a330

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 1e533f4c3a6f3634c2e3ab80a0e4b14b1ecedc38
=> Config: regenerating based on 1e533f4c3a6f3634c2e3ab80a0e4b14b1ecedc38

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 3d8d2a71480a7392bf9021b1642115cf8782ee86
=> Config: regenerating based on 3d8d2a71480a7392bf9021b1642115cf8782ee86

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 3f0989157100ee306e1c898962b9cd9ebfcaa64f
=> Config: regenerating based on 3f0989157100ee306e1c898962b9cd9ebfcaa64f

config/resource-manager.hcl
Updating the Resource Manager configuration based on the commit 0391a79988bcd240b45002bb2c4f860f3bc4fb1c
=> Config: regenerating based on 0391a79988bcd240b45002bb2c4f860f3bc4fb1c

config/resource-manager.hcl
fixes https://github.com/hashicorp/pandora/issues/4950
=> add containerservice@2025-07-01
